# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from freestyle_client.models.additional_repository import AdditionalRepository
from freestyle_client.models.dev_server_preset import DevServerPreset
from freestyle_client.models.freestyle_file import FreestyleFile
from freestyle_client.models.linux_group_spec import LinuxGroupSpec
from freestyle_client.models.linux_user_spec import LinuxUserSpec
from freestyle_client.models.port_config import PortConfig
from freestyle_client.models.systemd_config_internal import SystemdConfigInternal
from typing import Optional, Set
from typing_extensions import Self

class DevServerRequestV2(BaseModel):
    """
    DevServerRequestV2
    """ # noqa: E501
    dev_command: Optional[StrictStr] = Field(default=None, alias="devCommand")
    install_command: Optional[StrictStr] = Field(default=None, alias="installCommand")
    timeout: Optional[StrictInt] = None
    env_vars: Optional[Dict[str, StrictStr]] = Field(default=None, alias="envVars")
    ports: Optional[List[PortConfig]] = None
    preset: Optional[DevServerPreset] = DevServerPreset.AUTO
    systemd: Optional[SystemdConfigInternal] = None
    users: Optional[List[LinuxUserSpec]] = None
    groups: Optional[List[LinuxGroupSpec]] = None
    additional_files: Optional[Dict[str, FreestyleFile]] = Field(default=None, alias="additionalFiles")
    web_terminal: Optional[StrictBool] = Field(default=None, alias="webTerminal")
    web_vscode: Optional[StrictBool] = Field(default=None, alias="webVscode")
    additional_repositories: Optional[List[AdditionalRepository]] = Field(default=None, alias="additionalRepositories")
    repo_id: Optional[StrictStr] = Field(default=None, alias="repoId")
    git_ref: Optional[StrictStr] = Field(default=None, alias="gitRef")
    force_new: Optional[StrictBool] = Field(default=None, description="By default dev servers will find a matching session, with forceNew is true it will always create a new one", alias="forceNew")
    __properties: ClassVar[List[str]] = ["devCommand", "installCommand", "timeout", "envVars", "ports", "preset", "systemd", "users", "groups", "additionalFiles", "webTerminal", "webVscode", "additionalRepositories", "repoId", "gitRef", "forceNew"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DevServerRequestV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ports (list)
        _items = []
        if self.ports:
            for _item_ports in self.ports:
                if _item_ports:
                    _items.append(_item_ports.to_dict())
            _dict['ports'] = _items
        # override the default output from pydantic by calling `to_dict()` of systemd
        if self.systemd:
            _dict['systemd'] = self.systemd.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_item_users.to_dict())
            _dict['users'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in additional_files (dict)
        _field_dict = {}
        if self.additional_files:
            for _key_additional_files in self.additional_files:
                if self.additional_files[_key_additional_files]:
                    _field_dict[_key_additional_files] = self.additional_files[_key_additional_files].to_dict()
            _dict['additionalFiles'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in additional_repositories (list)
        _items = []
        if self.additional_repositories:
            for _item_additional_repositories in self.additional_repositories:
                if _item_additional_repositories:
                    _items.append(_item_additional_repositories.to_dict())
            _dict['additionalRepositories'] = _items
        # set to None if dev_command (nullable) is None
        # and model_fields_set contains the field
        if self.dev_command is None and "dev_command" in self.model_fields_set:
            _dict['devCommand'] = None

        # set to None if install_command (nullable) is None
        # and model_fields_set contains the field
        if self.install_command is None and "install_command" in self.model_fields_set:
            _dict['installCommand'] = None

        # set to None if timeout (nullable) is None
        # and model_fields_set contains the field
        if self.timeout is None and "timeout" in self.model_fields_set:
            _dict['timeout'] = None

        # set to None if ports (nullable) is None
        # and model_fields_set contains the field
        if self.ports is None and "ports" in self.model_fields_set:
            _dict['ports'] = None

        # set to None if preset (nullable) is None
        # and model_fields_set contains the field
        if self.preset is None and "preset" in self.model_fields_set:
            _dict['preset'] = None

        # set to None if systemd (nullable) is None
        # and model_fields_set contains the field
        if self.systemd is None and "systemd" in self.model_fields_set:
            _dict['systemd'] = None

        # set to None if users (nullable) is None
        # and model_fields_set contains the field
        if self.users is None and "users" in self.model_fields_set:
            _dict['users'] = None

        # set to None if groups (nullable) is None
        # and model_fields_set contains the field
        if self.groups is None and "groups" in self.model_fields_set:
            _dict['groups'] = None

        # set to None if web_terminal (nullable) is None
        # and model_fields_set contains the field
        if self.web_terminal is None and "web_terminal" in self.model_fields_set:
            _dict['webTerminal'] = None

        # set to None if web_vscode (nullable) is None
        # and model_fields_set contains the field
        if self.web_vscode is None and "web_vscode" in self.model_fields_set:
            _dict['webVscode'] = None

        # set to None if additional_repositories (nullable) is None
        # and model_fields_set contains the field
        if self.additional_repositories is None and "additional_repositories" in self.model_fields_set:
            _dict['additionalRepositories'] = None

        # set to None if repo_id (nullable) is None
        # and model_fields_set contains the field
        if self.repo_id is None and "repo_id" in self.model_fields_set:
            _dict['repoId'] = None

        # set to None if git_ref (nullable) is None
        # and model_fields_set contains the field
        if self.git_ref is None and "git_ref" in self.model_fields_set:
            _dict['gitRef'] = None

        # set to None if force_new (nullable) is None
        # and model_fields_set contains the field
        if self.force_new is None and "force_new" in self.model_fields_set:
            _dict['forceNew'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DevServerRequestV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "devCommand": obj.get("devCommand"),
            "installCommand": obj.get("installCommand"),
            "timeout": obj.get("timeout"),
            "envVars": obj.get("envVars"),
            "ports": [PortConfig.from_dict(_item) for _item in obj["ports"]] if obj.get("ports") is not None else None,
            "preset": obj.get("preset") if obj.get("preset") is not None else DevServerPreset.AUTO,
            "systemd": SystemdConfigInternal.from_dict(obj["systemd"]) if obj.get("systemd") is not None else None,
            "users": [LinuxUserSpec.from_dict(_item) for _item in obj["users"]] if obj.get("users") is not None else None,
            "groups": [LinuxGroupSpec.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "additionalFiles": dict(
                (_k, FreestyleFile.from_dict(_v))
                for _k, _v in obj["additionalFiles"].items()
            )
            if obj.get("additionalFiles") is not None
            else None,
            "webTerminal": obj.get("webTerminal"),
            "webVscode": obj.get("webVscode"),
            "additionalRepositories": [AdditionalRepository.from_dict(_item) for _item in obj["additionalRepositories"]] if obj.get("additionalRepositories") is not None else None,
            "repoId": obj.get("repoId"),
            "gitRef": obj.get("gitRef"),
            "forceNew": obj.get("forceNew")
        })
        return _obj


