# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from freestyle_client.models.diff_file_status import DiffFileStatus
from typing import Optional, Set
from typing_extensions import Self

class DiffFile(BaseModel):
    """
    A file that was changed in the comparison
    """ # noqa: E501
    sha: Optional[StrictStr] = Field(default=None, description="The blob SHA of the file")
    filename: StrictStr = Field(description="The file path")
    status: DiffFileStatus = Field(description="The status of the file (added, removed, modified, renamed, copied, changed, unchanged)")
    additions: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of lines added")
    deletions: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of lines deleted")
    changes: Annotated[int, Field(strict=True, ge=0)] = Field(description="Total number of changes (additions + deletions)")
    previous_filename: Optional[StrictStr] = Field(default=None, description="Previous filename (for renamed/copied files)")
    __properties: ClassVar[List[str]] = ["sha", "filename", "status", "additions", "deletions", "changes", "previous_filename"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiffFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sha (nullable) is None
        # and model_fields_set contains the field
        if self.sha is None and "sha" in self.model_fields_set:
            _dict['sha'] = None

        # set to None if previous_filename (nullable) is None
        # and model_fields_set contains the field
        if self.previous_filename is None and "previous_filename" in self.model_fields_set:
            _dict['previous_filename'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiffFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sha": obj.get("sha"),
            "filename": obj.get("filename"),
            "status": obj.get("status"),
            "additions": obj.get("additions"),
            "deletions": obj.get("deletions"),
            "changes": obj.get("changes"),
            "previous_filename": obj.get("previous_filename")
        })
        return _obj


