# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from freestyle_client.models.port_mapping import PortMapping
from freestyle_client.models.vm_persistence import VmPersistence
from typing import Optional, Set
from typing_extensions import Self

class ForkVmRequest(BaseModel):
    """
    ForkVmRequest
    """ # noqa: E501
    idle_timeout_seconds: Optional[StrictInt] = Field(default=None, alias="idleTimeoutSeconds")
    ports: Optional[List[PortMapping]] = Field(default=None, description="Optional list of ports to expose externally. If not provided, port 3000 will be exposed on port 443 by default. Pass an empty array to disable external ports. Only ports 8081 and 443 can be configured externally for now. Any target port is allowed.")
    ready_signal_timeout_seconds: Optional[StrictInt] = Field(default=None, description="Whether the api request should wait for the VM to be ready before returning. By default, the VM is considered ready when the serial console is ready for login.", alias="readySignalTimeoutSeconds")
    wait_for_ready_signal: Optional[StrictBool] = Field(default=None, description="How long to wait for the ready signal before timing out. Defaults to 120 seconds if not provided.", alias="waitForReadySignal")
    workdir: Optional[StrictStr] = Field(default=None, description="Optional working directory for the VM. File system and shell commands will be executed in this directory.")
    persistence: Optional[VmPersistence] = Field(default=None, description="Persistence strategy for the VM. If not provided, defaults to 'sticky' with priority 5.")
    __properties: ClassVar[List[str]] = ["idleTimeoutSeconds", "ports", "readySignalTimeoutSeconds", "waitForReadySignal", "workdir", "persistence"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ForkVmRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ports (list)
        _items = []
        if self.ports:
            for _item_ports in self.ports:
                if _item_ports:
                    _items.append(_item_ports.to_dict())
            _dict['ports'] = _items
        # override the default output from pydantic by calling `to_dict()` of persistence
        if self.persistence:
            _dict['persistence'] = self.persistence.to_dict()
        # set to None if idle_timeout_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.idle_timeout_seconds is None and "idle_timeout_seconds" in self.model_fields_set:
            _dict['idleTimeoutSeconds'] = None

        # set to None if ports (nullable) is None
        # and model_fields_set contains the field
        if self.ports is None and "ports" in self.model_fields_set:
            _dict['ports'] = None

        # set to None if ready_signal_timeout_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.ready_signal_timeout_seconds is None and "ready_signal_timeout_seconds" in self.model_fields_set:
            _dict['readySignalTimeoutSeconds'] = None

        # set to None if wait_for_ready_signal (nullable) is None
        # and model_fields_set contains the field
        if self.wait_for_ready_signal is None and "wait_for_ready_signal" in self.model_fields_set:
            _dict['waitForReadySignal'] = None

        # set to None if workdir (nullable) is None
        # and model_fields_set contains the field
        if self.workdir is None and "workdir" in self.model_fields_set:
            _dict['workdir'] = None

        # set to None if persistence (nullable) is None
        # and model_fields_set contains the field
        if self.persistence is None and "persistence" in self.model_fields_set:
            _dict['persistence'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ForkVmRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "idleTimeoutSeconds": obj.get("idleTimeoutSeconds"),
            "ports": [PortMapping.from_dict(_item) for _item in obj["ports"]] if obj.get("ports") is not None else None,
            "readySignalTimeoutSeconds": obj.get("readySignalTimeoutSeconds") if obj.get("readySignalTimeoutSeconds") is not None else true,
            "waitForReadySignal": obj.get("waitForReadySignal"),
            "workdir": obj.get("workdir"),
            "persistence": VmPersistence.from_dict(obj["persistence"]) if obj.get("persistence") is not None else None
        })
        return _obj


