# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from freestyle_client.models.deployment_build_options import DeploymentBuildOptions
from freestyle_client.models.freestyle_network_permission import FreestyleNetworkPermission
from typing import Optional, Set
from typing_extensions import Self

class FreestyleDeployWebConfiguration(BaseModel):
    """
    FreestyleDeployWebConfiguration
    """ # noqa: E501
    domains: Optional[List[StrictStr]] = None
    entrypoint: Optional[StrictStr] = None
    env_vars: Optional[Dict[str, StrictStr]] = Field(default=None, alias="envVars")
    node_modules: Optional[Dict[str, StrictStr]] = Field(default=None, alias="nodeModules")
    timeout: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    server_start_check: Optional[StrictBool] = Field(default=None, alias="serverStartCheck")
    network_permissions: Optional[List[FreestyleNetworkPermission]] = Field(default=None, alias="networkPermissions")
    build: Optional[DeploymentBuildOptions] = None
    var_await: Optional[StrictBool] = Field(default=None, alias="await")
    __properties: ClassVar[List[str]] = ["domains", "entrypoint", "envVars", "nodeModules", "timeout", "serverStartCheck", "networkPermissions", "build", "await"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FreestyleDeployWebConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in network_permissions (list)
        _items = []
        if self.network_permissions:
            for _item_network_permissions in self.network_permissions:
                if _item_network_permissions:
                    _items.append(_item_network_permissions.to_dict())
            _dict['networkPermissions'] = _items
        # override the default output from pydantic by calling `to_dict()` of build
        if self.build:
            _dict['build'] = self.build.to_dict()
        # set to None if domains (nullable) is None
        # and model_fields_set contains the field
        if self.domains is None and "domains" in self.model_fields_set:
            _dict['domains'] = None

        # set to None if entrypoint (nullable) is None
        # and model_fields_set contains the field
        if self.entrypoint is None and "entrypoint" in self.model_fields_set:
            _dict['entrypoint'] = None

        # set to None if timeout (nullable) is None
        # and model_fields_set contains the field
        if self.timeout is None and "timeout" in self.model_fields_set:
            _dict['timeout'] = None

        # set to None if server_start_check (nullable) is None
        # and model_fields_set contains the field
        if self.server_start_check is None and "server_start_check" in self.model_fields_set:
            _dict['serverStartCheck'] = None

        # set to None if network_permissions (nullable) is None
        # and model_fields_set contains the field
        if self.network_permissions is None and "network_permissions" in self.model_fields_set:
            _dict['networkPermissions'] = None

        # set to None if build (nullable) is None
        # and model_fields_set contains the field
        if self.build is None and "build" in self.model_fields_set:
            _dict['build'] = None

        # set to None if var_await (nullable) is None
        # and model_fields_set contains the field
        if self.var_await is None and "var_await" in self.model_fields_set:
            _dict['await'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FreestyleDeployWebConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domains": obj.get("domains"),
            "entrypoint": obj.get("entrypoint"),
            "envVars": obj.get("envVars"),
            "nodeModules": obj.get("nodeModules"),
            "timeout": obj.get("timeout"),
            "serverStartCheck": obj.get("serverStartCheck"),
            "networkPermissions": [FreestyleNetworkPermission.from_dict(_item) for _item in obj["networkPermissions"]] if obj.get("networkPermissions") is not None else None,
            "build": DeploymentBuildOptions.from_dict(obj["build"]) if obj.get("build") is not None else None,
            "await": obj.get("await")
        })
        return _obj


