# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from freestyle_client.models.systemd_restart_policy import SystemdRestartPolicy
from freestyle_client.models.systemd_unit_mode import SystemdUnitMode
from typing import Optional, Set
from typing_extensions import Self

class SystemdUnitSpecPatch(BaseModel):
    """
    SystemdUnitSpecPatch
    """ # noqa: E501
    name: StrictStr = Field(description="Unique slug; becomes unit name \"<name>.service\".")
    mode: Optional[SystemdUnitMode] = Field(default=None, description="\"oneshot\" (run and exit) or \"service\" (long-running/healing).")
    var_exec: Optional[List[StrictStr]] = Field(default=None, description="Executable to run (can specify multiple commands that run sequentially).", alias="exec")
    env: Optional[Dict[str, StrictStr]] = Field(default=None, description="Environment variables.")
    user: Optional[StrictStr] = Field(default=None, description="Linux user to run the service as.")
    group: Optional[StrictStr] = Field(default=None, description="Linux group to run the service in.")
    workdir: Optional[StrictStr] = Field(default=None, description="Working directory.")
    after: Optional[List[StrictStr]] = Field(default=None, description="Establishes an ordering dependency. The current unit will start only after the units listed in After= have started. This is useful for ensuring that certain services are up and running before the current service begins its operation.")
    requires: Optional[List[StrictStr]] = Field(default=None, description="Establishes a strong dependency. If the required unit fails to start or stops unexpectedly, the current unit will also be stopped. This ensures that a service critical to the functioning of the current unit is running and stable. Units listed in Requires= are activated along with the current unit. If the required unit is not active, systemd will attempt to start it. This directive signifies a tight coupling between services, where the current service cannot function without the required service.")
    on_failure: Optional[List[StrictStr]] = Field(default=None, description="Units to activate when this unit enters a failed state. This is useful for triggering recovery actions, notifications, or cleanup services when the current service fails.", alias="onFailure")
    wanted_by: Optional[List[StrictStr]] = Field(default=None, description="Target used when enabling (default: multi-user.target).", alias="wantedBy")
    enable: Optional[StrictBool] = Field(default=None, description="Whether to enable this service (calls `systemctl enable <service>`). When enabled, the service will start automatically at boot.")
    timeout_sec: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Overall start/stop timeout.", alias="timeoutSec")
    delete_after_success: Optional[StrictBool] = Field(default=None, description="For oneshot: remove unit on success.", alias="deleteAfterSuccess")
    ready_signal: Optional[StrictBool] = Field(default=None, description="Use sd_notify; maps to Type=notify.", alias="readySignal")
    watchdog_sec: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Enable systemd watchdog (seconds).", alias="watchdogSec")
    restart_policy: Optional[SystemdRestartPolicy] = Field(default=None, description="Restart semantics (service mode).", alias="restartPolicy")
    __properties: ClassVar[List[str]] = ["name", "mode", "exec", "env", "user", "group", "workdir", "after", "requires", "onFailure", "wantedBy", "enable", "timeoutSec", "deleteAfterSuccess", "readySignal", "watchdogSec", "restartPolicy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemdUnitSpecPatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of restart_policy
        if self.restart_policy:
            _dict['restartPolicy'] = self.restart_policy.to_dict()
        # set to None if mode (nullable) is None
        # and model_fields_set contains the field
        if self.mode is None and "mode" in self.model_fields_set:
            _dict['mode'] = None

        # set to None if var_exec (nullable) is None
        # and model_fields_set contains the field
        if self.var_exec is None and "var_exec" in self.model_fields_set:
            _dict['exec'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        # set to None if group (nullable) is None
        # and model_fields_set contains the field
        if self.group is None and "group" in self.model_fields_set:
            _dict['group'] = None

        # set to None if workdir (nullable) is None
        # and model_fields_set contains the field
        if self.workdir is None and "workdir" in self.model_fields_set:
            _dict['workdir'] = None

        # set to None if after (nullable) is None
        # and model_fields_set contains the field
        if self.after is None and "after" in self.model_fields_set:
            _dict['after'] = None

        # set to None if requires (nullable) is None
        # and model_fields_set contains the field
        if self.requires is None and "requires" in self.model_fields_set:
            _dict['requires'] = None

        # set to None if on_failure (nullable) is None
        # and model_fields_set contains the field
        if self.on_failure is None and "on_failure" in self.model_fields_set:
            _dict['onFailure'] = None

        # set to None if wanted_by (nullable) is None
        # and model_fields_set contains the field
        if self.wanted_by is None and "wanted_by" in self.model_fields_set:
            _dict['wantedBy'] = None

        # set to None if enable (nullable) is None
        # and model_fields_set contains the field
        if self.enable is None and "enable" in self.model_fields_set:
            _dict['enable'] = None

        # set to None if timeout_sec (nullable) is None
        # and model_fields_set contains the field
        if self.timeout_sec is None and "timeout_sec" in self.model_fields_set:
            _dict['timeoutSec'] = None

        # set to None if delete_after_success (nullable) is None
        # and model_fields_set contains the field
        if self.delete_after_success is None and "delete_after_success" in self.model_fields_set:
            _dict['deleteAfterSuccess'] = None

        # set to None if ready_signal (nullable) is None
        # and model_fields_set contains the field
        if self.ready_signal is None and "ready_signal" in self.model_fields_set:
            _dict['readySignal'] = None

        # set to None if watchdog_sec (nullable) is None
        # and model_fields_set contains the field
        if self.watchdog_sec is None and "watchdog_sec" in self.model_fields_set:
            _dict['watchdogSec'] = None

        # set to None if restart_policy (nullable) is None
        # and model_fields_set contains the field
        if self.restart_policy is None and "restart_policy" in self.model_fields_set:
            _dict['restartPolicy'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemdUnitSpecPatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "mode": obj.get("mode"),
            "exec": obj.get("exec"),
            "env": obj.get("env"),
            "user": obj.get("user"),
            "group": obj.get("group"),
            "workdir": obj.get("workdir"),
            "after": obj.get("after"),
            "requires": obj.get("requires"),
            "onFailure": obj.get("onFailure"),
            "wantedBy": obj.get("wantedBy"),
            "enable": obj.get("enable"),
            "timeoutSec": obj.get("timeoutSec"),
            "deleteAfterSuccess": obj.get("deleteAfterSuccess"),
            "readySignal": obj.get("readySignal"),
            "watchdogSec": obj.get("watchdogSec"),
            "restartPolicy": SystemdRestartPolicy.from_dict(obj["restartPolicy"]) if obj.get("restartPolicy") is not None else None
        })
        return _obj


