# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from freestyle_client.models.freestyle_file import FreestyleFile
from freestyle_client.models.git_repository_spec import GitRepositorySpec
from freestyle_client.models.linux_group_spec import LinuxGroupSpec
from freestyle_client.models.linux_user_spec import LinuxUserSpec
from freestyle_client.models.systemd_config import SystemdConfig
from freestyle_client.models.vm_persistence import VmPersistence
from freestyle_client.models.vm_template_ports_inner import VmTemplatePortsInner
from typing import Optional, Set
from typing_extensions import Self

class VmTemplate(BaseModel):
    """
    VmTemplate
    """ # noqa: E501
    snapshot_id: Optional[StrictStr] = Field(default=None, description="Optional snapshot ID to create a VM from. If provided, the new VM will be created from the specified snapshot. Cannot be used together with fork_vm_id or docker_image.", alias="snapshotId")
    rootfs_size_mb: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=16000, description="Size of the ext4 rootfs in MB. Defaults to 16000MB if not provided.", alias="rootfsSizeMb")
    workdir: Optional[StrictStr] = Field(default=None, description="Optional working directory for the VM. If not provided, the default to '/'")
    idle_timeout_seconds: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Idle timeout in seconds. If set, the VM will be automatically suspended after this many seconds of no network activity. Defaults to 300 seconds (5 minutes) if not provided or the last used timeout for the forked VM.", alias="idleTimeoutSeconds")
    wait_for_ready_signal: Optional[StrictBool] = Field(default=None, alias="waitForReadySignal")
    ready_signal_timeout_seconds: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="readySignalTimeoutSeconds")
    persistence: Optional[VmPersistence] = Field(default=None, description="Persistence strategy for the VM. If not provided, defaults to 'sticky' with priority 5.")
    ports: Optional[List[VmTemplatePortsInner]] = Field(default=None, description="Optional list of ports to expose externally. If not provided, port 3000 will be exposed on port 443 by default. Pass an empty array to disable external ports. Only ports 8081 and 443 can be configured externally for now. Any target port is allowed.")
    systemd: Optional[SystemdConfig] = None
    users: Optional[List[LinuxUserSpec]] = Field(default=None, description="Linux users to create on VM startup")
    groups: Optional[List[LinuxGroupSpec]] = Field(default=None, description="Linux groups to create on VM startup")
    additional_files: Optional[Dict[str, FreestyleFile]] = Field(default=None, alias="additionalFiles")
    git_repos: Optional[List[GitRepositorySpec]] = Field(default=None, alias="gitRepos")
    discriminator: Optional[StrictStr] = Field(default=None, description="Optional discriminator to differentiate snapshots with otherwise identical configurations")
    __properties: ClassVar[List[str]] = ["snapshotId", "rootfsSizeMb", "workdir", "idleTimeoutSeconds", "waitForReadySignal", "readySignalTimeoutSeconds", "persistence", "ports", "systemd", "users", "groups", "additionalFiles", "gitRepos", "discriminator"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VmTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of persistence
        if self.persistence:
            _dict['persistence'] = self.persistence.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ports (list)
        _items = []
        if self.ports:
            for _item_ports in self.ports:
                if _item_ports:
                    _items.append(_item_ports.to_dict())
            _dict['ports'] = _items
        # override the default output from pydantic by calling `to_dict()` of systemd
        if self.systemd:
            _dict['systemd'] = self.systemd.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_item_users.to_dict())
            _dict['users'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in additional_files (dict)
        _field_dict = {}
        if self.additional_files:
            for _key_additional_files in self.additional_files:
                if self.additional_files[_key_additional_files]:
                    _field_dict[_key_additional_files] = self.additional_files[_key_additional_files].to_dict()
            _dict['additionalFiles'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in git_repos (list)
        _items = []
        if self.git_repos:
            for _item_git_repos in self.git_repos:
                if _item_git_repos:
                    _items.append(_item_git_repos.to_dict())
            _dict['gitRepos'] = _items
        # set to None if snapshot_id (nullable) is None
        # and model_fields_set contains the field
        if self.snapshot_id is None and "snapshot_id" in self.model_fields_set:
            _dict['snapshotId'] = None

        # set to None if rootfs_size_mb (nullable) is None
        # and model_fields_set contains the field
        if self.rootfs_size_mb is None and "rootfs_size_mb" in self.model_fields_set:
            _dict['rootfsSizeMb'] = None

        # set to None if workdir (nullable) is None
        # and model_fields_set contains the field
        if self.workdir is None and "workdir" in self.model_fields_set:
            _dict['workdir'] = None

        # set to None if idle_timeout_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.idle_timeout_seconds is None and "idle_timeout_seconds" in self.model_fields_set:
            _dict['idleTimeoutSeconds'] = None

        # set to None if wait_for_ready_signal (nullable) is None
        # and model_fields_set contains the field
        if self.wait_for_ready_signal is None and "wait_for_ready_signal" in self.model_fields_set:
            _dict['waitForReadySignal'] = None

        # set to None if ready_signal_timeout_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.ready_signal_timeout_seconds is None and "ready_signal_timeout_seconds" in self.model_fields_set:
            _dict['readySignalTimeoutSeconds'] = None

        # set to None if persistence (nullable) is None
        # and model_fields_set contains the field
        if self.persistence is None and "persistence" in self.model_fields_set:
            _dict['persistence'] = None

        # set to None if ports (nullable) is None
        # and model_fields_set contains the field
        if self.ports is None and "ports" in self.model_fields_set:
            _dict['ports'] = None

        # set to None if systemd (nullable) is None
        # and model_fields_set contains the field
        if self.systemd is None and "systemd" in self.model_fields_set:
            _dict['systemd'] = None

        # set to None if users (nullable) is None
        # and model_fields_set contains the field
        if self.users is None and "users" in self.model_fields_set:
            _dict['users'] = None

        # set to None if groups (nullable) is None
        # and model_fields_set contains the field
        if self.groups is None and "groups" in self.model_fields_set:
            _dict['groups'] = None

        # set to None if git_repos (nullable) is None
        # and model_fields_set contains the field
        if self.git_repos is None and "git_repos" in self.model_fields_set:
            _dict['gitRepos'] = None

        # set to None if discriminator (nullable) is None
        # and model_fields_set contains the field
        if self.discriminator is None and "discriminator" in self.model_fields_set:
            _dict['discriminator'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VmTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "snapshotId": obj.get("snapshotId"),
            "rootfsSizeMb": obj.get("rootfsSizeMb") if obj.get("rootfsSizeMb") is not None else 16000,
            "workdir": obj.get("workdir"),
            "idleTimeoutSeconds": obj.get("idleTimeoutSeconds"),
            "waitForReadySignal": obj.get("waitForReadySignal"),
            "readySignalTimeoutSeconds": obj.get("readySignalTimeoutSeconds"),
            "persistence": VmPersistence.from_dict(obj["persistence"]) if obj.get("persistence") is not None else None,
            "ports": [VmTemplatePortsInner.from_dict(_item) for _item in obj["ports"]] if obj.get("ports") is not None else None,
            "systemd": SystemdConfig.from_dict(obj["systemd"]) if obj.get("systemd") is not None else None,
            "users": [LinuxUserSpec.from_dict(_item) for _item in obj["users"]] if obj.get("users") is not None else None,
            "groups": [LinuxGroupSpec.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "additionalFiles": dict(
                (_k, FreestyleFile.from_dict(_v))
                for _k, _v in obj["additionalFiles"].items()
            )
            if obj.get("additionalFiles") is not None
            else None,
            "gitRepos": [GitRepositorySpec.from_dict(_item) for _item in obj["gitRepos"]] if obj.get("gitRepos") is not None else None,
            "discriminator": obj.get("discriminator")
        })
        return _obj


