name: cmux
options:
  bundleIdPrefix: dev.cmux
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"

packages:
  ConvexMobile:
    url: https://github.com/get-convex/convex-swift
    from: "0.1.0"

targets:
  cmux:
    type: application
    platform: iOS
    sources:
      - Sources
      - Assets.xcassets
    dependencies:
      - package: ConvexMobile
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: dev.cmux.app
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: "YES"
      SWIFT_EMIT_LOC_STRINGS: "YES"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
