import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
  server: {
    STACK_WEBHOOK_SECRET: z.string().min(1),
    // Stack Admin keys for backfills and server-side operations
    STACK_SECRET_SERVER_KEY: z.string().min(1).optional(),
    STACK_SUPER_SECRET_ADMIN_KEY: z.string().min(1).optional(),
    NEXT_PUBLIC_STACK_PROJECT_ID: z.string().optional(),
    NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: z.string().optional(),
    STACK_API_BASE_URL: z.string().url().optional(),
    STACK_APPLE_CLIENT_IDS: z.string().min(1).optional(),
    GITHUB_APP_WEBHOOK_SECRET: z.string().min(1).optional(),
    INSTALL_STATE_SECRET: z.string().min(1).optional(),
    CMUX_GITHUB_APP_ID: z.string().min(1).optional(),
    CMUX_GITHUB_APP_PRIVATE_KEY: z.string().min(1).optional(),
    BASE_APP_URL: z.string().min(1),
    CMUX_TASK_RUN_JWT_SECRET: z.string().min(1),
    CMUX_CONVERSATION_JWT_SECRET: z.string().min(1).optional(),
    // ACP (Agent Client Protocol) settings
    ACP_CALLBACK_SECRET: z.string().min(1).optional(),
    CONVEX_SITE_URL: z.string().min(1).optional(),
    OPENAI_API_KEY: z.string().min(1).optional(),
    ANTHROPIC_API_KEY: z.string().min(1).optional(),
    VERTEX_PRIVATE_KEY: z.string().min(1).optional(),
    AWS_BEARER_TOKEN_BEDROCK: z.string().min(1).optional(),
    MORPH_API_KEY: z.string().min(1).optional(),
    FREESTYLE_API_KEY: z.string().min(1).optional(),
    DAYTONA_API_KEY: z.string().min(1).optional(),
    DAYTONA_TARGET: z.string().min(1).optional(),
    E2B_API_KEY: z.string().min(1).optional(),
    BLAXEL_API_KEY: z.string().min(1).optional(),
    BLAXEL_WORKSPACE: z.string().min(1).optional(),
    CMUX_IS_STAGING: z.string().optional(),
    CONVEX_IS_PRODUCTION: z.string().optional(),
    POSTHOG_API_KEY: z.string().optional(),
    SENTRY_DSN: z.string().min(1).optional(),
    AXIOM_DOMAIN: z.string().min(1).optional(),
    AXIOM_TOKEN: z.string().min(1).optional(),
    AXIOM_TRACES_DATASET: z.string().min(1).optional(),
  },
  runtimeEnv: process.env,
  emptyStringAsUndefined: true,
});
