# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.dev_server_configuration import DevServerConfiguration

class TestDevServerConfiguration(unittest.TestCase):
    """DevServerConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DevServerConfiguration:
        """Test DevServerConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DevServerConfiguration`
        """
        model = DevServerConfiguration()
        if include_optional:
            return DevServerConfiguration(
                dev_command = 'npm run dev',
                install_command = 'npm install',
                timeout = 30,
                env_vars = {RESEND_API_KEY=re_123456789},
                ports = [{externalPort=443, targetPort=3000}],
                preset = 'auto',
                systemd = freestyle_client.models.systemd_config_internal.SystemdConfigInternal(
                    enabled = False, 
                    services = [
                        freestyle_client.models.systemd_unit_spec.SystemdUnitSpec(
                            name = '', 
                            mode = 'oneshot', 
                            exec = [
                                ''
                                ], 
                            env = {
                                'key' : ''
                                }, 
                            user = '', 
                            group = '', 
                            workdir = '', 
                            after = [
                                ''
                                ], 
                            requires = [
                                ''
                                ], 
                            on_failure = [
                                ''
                                ], 
                            wanted_by = [
                                ''
                                ], 
                            enable = True, 
                            timeout_sec = 0, 
                            delete_after_success = True, 
                            remain_after_exit = True, 
                            ready_signal = True, 
                            watchdog_sec = 0, 
                            restart_policy = freestyle_client.models.systemd_restart_policy.SystemdRestartPolicy(
                                policy = 'no', 
                                restart_sec = 0, 
                                start_limit_burst = 0, 
                                start_limit_interval_sec = 0, ), )
                        ], 
                    patched_services = [
                        freestyle_client.models.systemd_unit_spec_patch.SystemdUnitSpecPatch(
                            name = '', 
                            user = '', 
                            group = '', 
                            workdir = '', 
                            enable = True, 
                            timeout_sec = 0, 
                            delete_after_success = True, 
                            ready_signal = True, 
                            watchdog_sec = 0, )
                        ], ),
                users = [
                    freestyle_client.models.linux_user_spec.LinuxUserSpec(
                        name = '', 
                        uid = 0, 
                        gecos = '', 
                        groups = [
                            ''
                            ], 
                        home = '', 
                        shell = '', 
                        system = True, )
                    ],
                groups = [
                    freestyle_client.models.linux_group_spec.LinuxGroupSpec(
                        name = '', 
                        gid = 0, 
                        system = True, )
                    ],
                additional_files = {
                    'key' : freestyle_client.models.freestyle_file.FreestyleFile(
                        content = '', 
                        encoding = '', )
                    },
                web_terminal = True,
                web_vscode = True,
                additional_repositories = [
                    freestyle_client.models.additional_repository.AdditionalRepository(
                        repository_id = '', 
                        path = '', )
                    ]
            )
        else:
            return DevServerConfiguration(
        )
        """

    def testDevServerConfiguration(self):
        """Test DevServerConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
