# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.api.git_api import GitApi


class TestGitApi(unittest.TestCase):
    """GitApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GitApi()

    def tearDown(self) -> None:
        pass

    def test_configure_github_sync(self) -> None:
        """Test case for configure_github_sync

        Configure GitHub sync for repository
        """
        pass

    def test_delete_dev_server_configuration(self) -> None:
        """Test case for delete_dev_server_configuration

        Delete dev server configuration
        """
        pass

    def test_get_dev_server_configuration(self) -> None:
        """Test case for get_dev_server_configuration

        Get dev server configuration
        """
        pass

    def test_get_github_sync(self) -> None:
        """Test case for get_github_sync

        Get GitHub sync configuration
        """
        pass

    def test_handle_compare_commits(self) -> None:
        """Test case for handle_compare_commits

        Compare two commits
        """
        pass

    def test_handle_create_git_trigger(self) -> None:
        """Test case for handle_create_git_trigger

        Create a git trigger
        """
        pass

    def test_handle_create_repo(self) -> None:
        """Test case for handle_create_repo

        Create a repository
        """
        pass

    def test_handle_delete_git_trigger(self) -> None:
        """Test case for handle_delete_git_trigger

        Delete a git trigger
        """
        pass

    def test_handle_delete_repo(self) -> None:
        """Test case for handle_delete_repo

        Delete a repository
        """
        pass

    def test_handle_download_tarball(self) -> None:
        """Test case for handle_download_tarball

        Download a tarball of a repo
        """
        pass

    def test_handle_download_zip(self) -> None:
        """Test case for handle_download_zip

        Download a zip of a repo
        """
        pass

    def test_handle_get_blob(self) -> None:
        """Test case for handle_get_blob

        Get a blob object
        """
        pass

    def test_handle_get_commit(self) -> None:
        """Test case for handle_get_commit

        Get a commit object
        """
        pass

    def test_handle_get_contents(self) -> None:
        """Test case for handle_get_contents

        Get the contents of a file or directory
        """
        pass

    def test_handle_get_default_branch(self) -> None:
        """Test case for handle_get_default_branch

        Get repository default branch
        """
        pass

    def test_handle_get_ref_branch(self) -> None:
        """Test case for handle_get_ref_branch

        Get a branch reference
        """
        pass

    def test_handle_get_ref_tag(self) -> None:
        """Test case for handle_get_ref_tag

        Get a tag reference
        """
        pass

    def test_handle_get_repo_info(self) -> None:
        """Test case for handle_get_repo_info

        Get repository information
        """
        pass

    def test_handle_get_tag(self) -> None:
        """Test case for handle_get_tag

        Get a tag object
        """
        pass

    def test_handle_get_tree(self) -> None:
        """Test case for handle_get_tree

        Get a tree object
        """
        pass

    def test_handle_list_commits(self) -> None:
        """Test case for handle_list_commits

        List commits for a repository
        """
        pass

    def test_handle_list_git_triggers(self) -> None:
        """Test case for handle_list_git_triggers

        List git triggers for a repository
        """
        pass

    def test_handle_list_repositories(self) -> None:
        """Test case for handle_list_repositories

        List repositories
        """
        pass

    def test_handle_set_default_branch(self) -> None:
        """Test case for handle_set_default_branch

        Set repository default branch
        """
        pass

    def test_remove_github_sync(self) -> None:
        """Test case for remove_github_sync

        Remove GitHub sync configuration
        """
        pass

    def test_update_dev_server_configuration(self) -> None:
        """Test case for update_dev_server_configuration

        Update dev server configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
