# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.api.web_api import WebApi


class TestWebApi(unittest.TestCase):
    """WebApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebApi()

    def tearDown(self) -> None:
        pass

    def test_handle_deploy_web_v2(self) -> None:
        """Test case for handle_deploy_web_v2

        Deploy a Website
        """
        pass

    def test_handle_get_web_deploy_details(self) -> None:
        """Test case for handle_get_web_deploy_details

        Get information on web deploy
        """
        pass

    def test_handle_list_web_deploys(self) -> None:
        """Test case for handle_list_web_deploys

        List web deploys
        """
        pass


if __name__ == '__main__':
    unittest.main()
