# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.api.vm_api import VMApi


class TestVMApi(unittest.TestCase):
    """VMApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VMApi()

    def tearDown(self) -> None:
        pass

    def test_create_snapshot(self) -> None:
        """Test case for create_snapshot

        """
        pass

    def test_create_vm(self) -> None:
        """Test case for create_vm

        """
        pass

    def test_delete_vm(self) -> None:
        """Test case for delete_vm

        """
        pass

    def test_exec_await(self) -> None:
        """Test case for exec_await

        """
        pass

    def test_fork_vm(self) -> None:
        """Test case for fork_vm

        """
        pass

    def test_get_file(self) -> None:
        """Test case for get_file

        """
        pass

    def test_get_terminal_logs(self) -> None:
        """Test case for get_terminal_logs

        """
        pass

    def test_get_terminal_xterm(self) -> None:
        """Test case for get_terminal_xterm

        """
        pass

    def test_get_vm(self) -> None:
        """Test case for get_vm

        """
        pass

    def test_kill_vm(self) -> None:
        """Test case for kill_vm

        """
        pass

    def test_list_snapshots(self) -> None:
        """Test case for list_snapshots

        """
        pass

    def test_list_terminals(self) -> None:
        """Test case for list_terminals

        """
        pass

    def test_list_vms(self) -> None:
        """Test case for list_vms

        """
        pass

    def test_optimize_vm(self) -> None:
        """Test case for optimize_vm

        """
        pass

    def test_put_file(self) -> None:
        """Test case for put_file

        """
        pass

    def test_resize_vm(self) -> None:
        """Test case for resize_vm

        """
        pass

    def test_snapshot_vm(self) -> None:
        """Test case for snapshot_vm

        """
        pass

    def test_start_vm(self) -> None:
        """Test case for start_vm

        """
        pass

    def test_stop_vm(self) -> None:
        """Test case for stop_vm

        """
        pass

    def test_suspend_vm(self) -> None:
        """Test case for suspend_vm

        """
        pass

    def test_wait_vm(self) -> None:
        """Test case for wait_vm

        """
        pass

    def test_watch_files(self) -> None:
        """Test case for watch_files

        """
        pass


if __name__ == '__main__':
    unittest.main()
