# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.api.deprecated_api import DeprecatedApi


class TestDeprecatedApi(unittest.TestCase):
    """DeprecatedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeprecatedApi()

    def tearDown(self) -> None:
        pass

    def test_handle_create_git_token(self) -> None:
        """Test case for handle_create_git_token

        Create an access token for an identity
        """
        pass

    def test_handle_create_identity(self) -> None:
        """Test case for handle_create_identity

        Create a Git identity
        """
        pass

    def test_handle_delete_identity(self) -> None:
        """Test case for handle_delete_identity

        Delete a Git identity
        """
        pass

    def test_handle_deploy_web(self) -> None:
        """Test case for handle_deploy_web

        Deploy a Website (v1)
        """
        pass

    def test_handle_describe_permission(self) -> None:
        """Test case for handle_describe_permission

        Get the permission of an identity on a repository
        """
        pass

    def test_handle_grant_permission(self) -> None:
        """Test case for handle_grant_permission

        Grant a permission to an identity
        """
        pass

    def test_handle_list_git_tokens(self) -> None:
        """Test case for handle_list_git_tokens

        List access tokens for an identity
        """
        pass

    def test_handle_list_identities(self) -> None:
        """Test case for handle_list_identities

        List Git identities
        """
        pass

    def test_handle_list_permissions(self) -> None:
        """Test case for handle_list_permissions

        List repository permissions for an identity
        """
        pass

    def test_handle_revoke_git_token(self) -> None:
        """Test case for handle_revoke_git_token

        Revoke an access token for an identity
        """
        pass

    def test_handle_revoke_permission(self) -> None:
        """Test case for handle_revoke_permission

        Revoke permissions from an identity
        """
        pass

    def test_handle_update_permission(self) -> None:
        """Test case for handle_update_permission

        Update a permission for an identity
        """
        pass


if __name__ == '__main__':
    unittest.main()
