# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.api.domains_api import DomainsApi


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainsApi()

    def tearDown(self) -> None:
        pass

    def test_handle_create_domain_verification(self) -> None:
        """Test case for handle_create_domain_verification

        Create a domain verification request
        """
        pass

    def test_handle_delete_domain_mapping(self) -> None:
        """Test case for handle_delete_domain_mapping

        Remove Domain Mapping
        """
        pass

    def test_handle_delete_domain_verification(self) -> None:
        """Test case for handle_delete_domain_verification

        Delete a domain verification request
        """
        pass

    def test_handle_insert_domain_mapping(self) -> None:
        """Test case for handle_insert_domain_mapping

        Insert Domain Mapping
        """
        pass

    def test_handle_list_domain_mappings(self) -> None:
        """Test case for handle_list_domain_mappings

        List Domain Mappings
        """
        pass

    def test_handle_list_domain_verification_requests(self) -> None:
        """Test case for handle_list_domain_verification_requests

        List domain verification requests for an account
        """
        pass

    def test_handle_list_domains(self) -> None:
        """Test case for handle_list_domains

        List domains for an account
        """
        pass

    def test_handle_verify_domain(self) -> None:
        """Test case for handle_verify_domain

        Verify a domain verification request
        """
        pass

    def test_handle_verify_wildcard(self) -> None:
        """Test case for handle_verify_wildcard

        Provision a wildcard certificate
        """
        pass


if __name__ == '__main__':
    unittest.main()
