# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.handle_ephemeral_dev_server200_response import HandleEphemeralDevServer200Response

class TestHandleEphemeralDevServer200Response(unittest.TestCase):
    """HandleEphemeralDevServer200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandleEphemeralDevServer200Response:
        """Test HandleEphemeralDevServer200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandleEphemeralDevServer200Response`
        """
        model = HandleEphemeralDevServer200Response()
        if include_optional:
            return HandleEphemeralDevServer200Response(
                url = '',
                is_new = True,
                dev_command_running = True,
                install_command_running = True,
                mcp_ephemeral_url = '',
                ephemeral_url = '',
                vm_id = '',
                base_id = ''
            )
        else:
            return HandleEphemeralDevServer200Response(
                url = '',
                is_new = True,
                dev_command_running = True,
                install_command_running = True,
        )
        """

    def testHandleEphemeralDevServer200Response(self):
        """Test HandleEphemeralDevServer200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
