# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.terminal_logs_array_response import TerminalLogsArrayResponse

class TestTerminalLogsArrayResponse(unittest.TestCase):
    """TerminalLogsArrayResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerminalLogsArrayResponse:
        """Test TerminalLogsArrayResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerminalLogsArrayResponse`
        """
        model = TerminalLogsArrayResponse()
        if include_optional:
            return TerminalLogsArrayResponse(
                logs = [
                    freestyle_client.models.log_entry.LogEntry(
                        line = '', 
                        timestamp = '', )
                    ]
            )
        else:
            return TerminalLogsArrayResponse(
                logs = [
                    freestyle_client.models.log_entry.LogEntry(
                        line = '', 
                        timestamp = '', )
                    ],
        )
        """

    def testTerminalLogsArrayResponse(self):
        """Test TerminalLogsArrayResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
