# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.handle_get_execute_run200_response import HandleGetExecuteRun200Response

class TestHandleGetExecuteRun200Response(unittest.TestCase):
    """HandleGetExecuteRun200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandleGetExecuteRun200Response:
        """Test HandleGetExecuteRun200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandleGetExecuteRun200Response`
        """
        model = HandleGetExecuteRun200Response()
        if include_optional:
            return HandleGetExecuteRun200Response(
                metadata = freestyle_client.models.execute_log_entry.ExecuteLogEntry(
                    deployment = '', 
                    account_id = '', 
                    provisioned_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    duration = '', 
                    state = 'starting', 
                    env_vars = {
                        'key' : ''
                        }, ),
                code = freestyle_client.models.execute_run_info.ExecuteRunInfo(
                    code = '', 
                    node_modules = {
                        'key' : ''
                        }, )
            )
        else:
            return HandleGetExecuteRun200Response(
                metadata = freestyle_client.models.execute_log_entry.ExecuteLogEntry(
                    deployment = '', 
                    account_id = '', 
                    provisioned_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    duration = '', 
                    state = 'starting', 
                    env_vars = {
                        'key' : ''
                        }, ),
        )
        """

    def testHandleGetExecuteRun200Response(self):
        """Test HandleGetExecuteRun200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
