# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.systemd_config_internal import SystemdConfigInternal

class TestSystemdConfigInternal(unittest.TestCase):
    """SystemdConfigInternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemdConfigInternal:
        """Test SystemdConfigInternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemdConfigInternal`
        """
        model = SystemdConfigInternal()
        if include_optional:
            return SystemdConfigInternal(
                enabled = False,
                services = [
                    freestyle_client.models.systemd_unit_spec.SystemdUnitSpec(
                        name = '', 
                        mode = 'oneshot', 
                        exec = [
                            ''
                            ], 
                        env = {
                            'key' : ''
                            }, 
                        user = '', 
                        group = '', 
                        workdir = '', 
                        after = [
                            ''
                            ], 
                        requires = [
                            ''
                            ], 
                        on_failure = [
                            ''
                            ], 
                        wanted_by = [
                            ''
                            ], 
                        enable = True, 
                        timeout_sec = 0, 
                        delete_after_success = True, 
                        remain_after_exit = True, 
                        ready_signal = True, 
                        watchdog_sec = 0, 
                        restart_policy = freestyle_client.models.systemd_restart_policy.SystemdRestartPolicy(
                            policy = 'no', 
                            restart_sec = 0, 
                            start_limit_burst = 0, 
                            start_limit_interval_sec = 0, ), )
                    ],
                patched_services = [
                    freestyle_client.models.systemd_unit_spec_patch.SystemdUnitSpecPatch(
                        name = '', 
                        mode = 'oneshot', 
                        exec = [
                            ''
                            ], 
                        env = {
                            'key' : ''
                            }, 
                        user = '', 
                        group = '', 
                        workdir = '', 
                        after = [
                            ''
                            ], 
                        requires = [
                            ''
                            ], 
                        on_failure = [
                            ''
                            ], 
                        wanted_by = [
                            ''
                            ], 
                        enable = True, 
                        timeout_sec = 0, 
                        delete_after_success = True, 
                        ready_signal = True, 
                        watchdog_sec = 0, 
                        restart_policy = freestyle_client.models.systemd_restart_policy.SystemdRestartPolicy(
                            policy = 'no', 
                            restart_sec = 0, 
                            start_limit_burst = 0, 
                            start_limit_interval_sec = 0, ), )
                    ]
            )
        else:
            return SystemdConfigInternal(
                enabled = False,
        )
        """

    def testSystemdConfigInternal(self):
        """Test SystemdConfigInternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
