# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.vm_template import VmTemplate

class TestVmTemplate(unittest.TestCase):
    """VmTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VmTemplate:
        """Test VmTemplate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VmTemplate`
        """
        model = VmTemplate()
        if include_optional:
            return VmTemplate(
                snapshot_id = '',
                rootfs_size_mb = 0,
                workdir = '',
                idle_timeout_seconds = 0,
                wait_for_ready_signal = True,
                ready_signal_timeout_seconds = 0,
                persistence = None,
                ports = [{port=443, targetPort=3000}],
                systemd = freestyle_client.models.systemd_config.SystemdConfig(
                    services = [
                        freestyle_client.models.systemd_unit_spec.SystemdUnitSpec(
                            name = '', 
                            mode = 'oneshot', 
                            exec = [
                                ''
                                ], 
                            env = {
                                'key' : ''
                                }, 
                            user = '', 
                            group = '', 
                            workdir = '', 
                            after = [
                                ''
                                ], 
                            requires = [
                                ''
                                ], 
                            on_failure = [
                                ''
                                ], 
                            wanted_by = [
                                ''
                                ], 
                            enable = True, 
                            timeout_sec = 0, 
                            delete_after_success = True, 
                            remain_after_exit = True, 
                            ready_signal = True, 
                            watchdog_sec = 0, 
                            restart_policy = freestyle_client.models.systemd_restart_policy.SystemdRestartPolicy(
                                policy = 'no', 
                                restart_sec = 0, 
                                start_limit_burst = 0, 
                                start_limit_interval_sec = 0, ), )
                        ], 
                    patched_services = [
                        freestyle_client.models.systemd_unit_spec_patch.SystemdUnitSpecPatch(
                            name = '', 
                            user = '', 
                            group = '', 
                            workdir = '', 
                            enable = True, 
                            timeout_sec = 0, 
                            delete_after_success = True, 
                            ready_signal = True, 
                            watchdog_sec = 0, )
                        ], ),
                users = [
                    freestyle_client.models.linux_user_spec.LinuxUserSpec(
                        name = '', 
                        uid = 0, 
                        gecos = '', 
                        groups = [
                            ''
                            ], 
                        home = '', 
                        shell = '', 
                        system = True, )
                    ],
                groups = [
                    freestyle_client.models.linux_group_spec.LinuxGroupSpec(
                        name = '', 
                        gid = 0, 
                        system = True, )
                    ],
                additional_files = {
                    'key' : freestyle_client.models.freestyle_file.FreestyleFile(
                        content = '', 
                        encoding = '', )
                    },
                git_repos = [
                    freestyle_client.models.git_repository_spec.GitRepositorySpec(
                        repo = '', 
                        path = '', 
                        rev = '', )
                    ],
                discriminator = ''
            )
        else:
            return VmTemplate(
        )
        """

    def testVmTemplate(self):
        """Test VmTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
