# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.handle_list_domains200_response_inner import HandleListDomains200ResponseInner

class TestHandleListDomains200ResponseInner(unittest.TestCase):
    """HandleListDomains200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandleListDomains200ResponseInner:
        """Test HandleListDomains200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandleListDomains200ResponseInner`
        """
        model = HandleListDomains200ResponseInner()
        if include_optional:
            return HandleListDomains200ResponseInner(
                domain = '',
                account_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                verified_dns = True,
                implicitly_owned = True,
                deploy_to_domain = True,
                manage_dns = True,
                deploy_to_subdomains = True
            )
        else:
            return HandleListDomains200ResponseInner(
                domain = '',
                account_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                verified_dns = True,
                implicitly_owned = True,
                deploy_to_domain = True,
                manage_dns = True,
                deploy_to_subdomains = True,
        )
        """

    def testHandleListDomains200ResponseInner(self):
        """Test HandleListDomains200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
