# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.freestyle_execute_script_params import FreestyleExecuteScriptParams

class TestFreestyleExecuteScriptParams(unittest.TestCase):
    """FreestyleExecuteScriptParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FreestyleExecuteScriptParams:
        """Test FreestyleExecuteScriptParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FreestyleExecuteScriptParams`
        """
        model = FreestyleExecuteScriptParams()
        if include_optional:
            return FreestyleExecuteScriptParams(
                script = 'export default () => {
  // get the value of the factorials of the numbers from 1 to 10 combined
  const a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  function factorial(n) {
    if (n === 0) {
      return 1;
    }
    return n * factorial(n - 1);
  }

  const b = a.map(factorial);

  return b.reduce((a, b) => a + b);
};
',
                config = freestyle_client.models.freestyle_execute_script_params_configuration.FreestyleExecuteScriptParamsConfiguration(
                    env_vars = {RESEND_API_KEY=re_123456789}, 
                    node_modules = {resend=4.0.1}, 
                    tags = [email], 
                    timeout = 0, 
                    peer_dependency_resolution = True, 
                    network_permissions = [
                        null
                        ], 
                    custom_headers = {
                        'key' : ''
                        }, 
                    proxy = 'https://aproxyyouown.com', )
            )
        else:
            return FreestyleExecuteScriptParams(
                script = 'export default () => {
  // get the value of the factorials of the numbers from 1 to 10 combined
  const a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  function factorial(n) {
    if (n === 0) {
      return 1;
    }
    return n * factorial(n - 1);
  }

  const b = a.map(factorial);

  return b.reduce((a, b) => a + b);
};
',
        )
        """

    def testFreestyleExecuteScriptParams(self):
        """Test FreestyleExecuteScriptParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
