# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.api.identity_api import IdentityApi


class TestIdentityApi(unittest.TestCase):
    """IdentityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IdentityApi()

    def tearDown(self) -> None:
        pass

    def test_handle_create_git_token(self) -> None:
        """Test case for handle_create_git_token

        Create an access token for an identity
        """
        pass

    def test_handle_create_identity(self) -> None:
        """Test case for handle_create_identity

        Create an identity
        """
        pass

    def test_handle_delete_identity(self) -> None:
        """Test case for handle_delete_identity

        Delete an identity
        """
        pass

    def test_handle_describe_git_permission(self) -> None:
        """Test case for handle_describe_git_permission

        Get the git permission of an identity on a repository
        """
        pass

    def test_handle_describe_vm_permission(self) -> None:
        """Test case for handle_describe_vm_permission

        Get VM permission details
        """
        pass

    def test_handle_grant_git_permission(self) -> None:
        """Test case for handle_grant_git_permission

        Grant a git repository permission to an identity
        """
        pass

    def test_handle_grant_vm_permission(self) -> None:
        """Test case for handle_grant_vm_permission

        Grant VM permission to an identity for a VM
        """
        pass

    def test_handle_list_git_permissions(self) -> None:
        """Test case for handle_list_git_permissions

        List repository permissions for an identity
        """
        pass

    def test_handle_list_git_tokens(self) -> None:
        """Test case for handle_list_git_tokens

        List access tokens for an identity
        """
        pass

    def test_handle_list_identities(self) -> None:
        """Test case for handle_list_identities

        List identities
        """
        pass

    def test_handle_list_vm_permissions(self) -> None:
        """Test case for handle_list_vm_permissions

        List VM permissions for an identity
        """
        pass

    def test_handle_revoke_git_permission(self) -> None:
        """Test case for handle_revoke_git_permission

        Revoke git repository permission from an identity
        """
        pass

    def test_handle_revoke_git_token(self) -> None:
        """Test case for handle_revoke_git_token

        Revoke an access token for an identity
        """
        pass

    def test_handle_revoke_vm_permission(self) -> None:
        """Test case for handle_revoke_vm_permission

        Revoke VM permission from an identity for a VM
        """
        pass

    def test_handle_update_allowed_users(self) -> None:
        """Test case for handle_update_allowed_users

        Update allowed users for VM permission
        """
        pass

    def test_handle_update_git_permission(self) -> None:
        """Test case for handle_update_git_permission

        Update a git repository permission for an identity
        """
        pass


if __name__ == '__main__':
    unittest.main()
