# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.freestyle_deploy_web_payload import FreestyleDeployWebPayload

class TestFreestyleDeployWebPayload(unittest.TestCase):
    """FreestyleDeployWebPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FreestyleDeployWebPayload:
        """Test FreestyleDeployWebPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FreestyleDeployWebPayload`
        """
        model = FreestyleDeployWebPayload()
        if include_optional:
            return FreestyleDeployWebPayload(
                files = {index.js={content=import http from 'node:http';\n// import { resolver } from './file2.js';\n\nconsole.log('starting server');\n\nconst server = http.createServer(async(req, res) => {\n  // wait 5 seconds before responding\n  // await new Promise((resolve) => setTimeout(resolve, 5000));\n  res.writeHead(200, { 'Content-Type': 'text/plain' });\n  res.end('Welcome to New York its been waiting for you');\n});\n\nserver.listen(3000, () => {\n  console.log('Server is running at http://localhost:3000');\n});}},
                config = freestyle_client.models.freestyle_deploy_web_configuration.FreestyleDeployWebConfiguration(
                    domains = [
                        ''
                        ], 
                    entrypoint = '', 
                    env_vars = {
                        'key' : ''
                        }, 
                    node_modules = {
                        'key' : ''
                        }, 
                    timeout = 0, 
                    server_start_check = True, 
                    network_permissions = [
                        null
                        ], 
                    build = null, 
                    await = True, )
            )
        else:
            return FreestyleDeployWebPayload(
                files = {index.js={content=import http from 'node:http';\n// import { resolver } from './file2.js';\n\nconsole.log('starting server');\n\nconst server = http.createServer(async(req, res) => {\n  // wait 5 seconds before responding\n  // await new Promise((resolve) => setTimeout(resolve, 5000));\n  res.writeHead(200, { 'Content-Type': 'text/plain' });\n  res.end('Welcome to New York its been waiting for you');\n});\n\nserver.listen(3000, () => {\n  console.log('Server is running at http://localhost:3000');\n});}},
        )
        """

    def testFreestyleDeployWebPayload(self):
        """Test FreestyleDeployWebPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
