# coding: utf-8

"""
    Freestyle Sandboxes

     Freestyle Sandboxes lets you deploy your users or AIs code. **Get your API Key at [admin.freestyle.sh](https://admin.freestyle.sh)**  They are broken up into core 5 categories: [Web](#tag/web), [Execute](#tag/execute), [Cloudstate](#tag/cloudstate), [Git](#tag/git), and [Domains](#tag/domains).  [Web](#tag/web): Send us the code for the website, we'll provision the certificates and get it hosted  [Execute](#tag/execute): Send us a function, we'll run it and send you the output  [Cloudstate](#tag/cloudstate): Our Opensource JavaScript Runtime used for cloud functions with persistent state  [Domains](#tag/domains): Manage your domains, including verification and listing  [Git](#tag/git): Manage your git repositories 

    The version of the OpenAPI document: 0.1.0
    Contact: ben@freestyle.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from freestyle_client.models.list_vms_response import ListVmsResponse

class TestListVmsResponse(unittest.TestCase):
    """ListVmsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListVmsResponse:
        """Test ListVmsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListVmsResponse`
        """
        model = ListVmsResponse()
        if include_optional:
            return ListVmsResponse(
                vms = [
                    freestyle_client.models.vm_info.VmInfo(
                        id = '', 
                        state = 'starting', 
                        metrics = freestyle_client.models.vm_metrics_info.VmMetricsInfo(
                            wall_time_seconds = 0, 
                            billing_day = '', 
                            is_active_today = True, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_network_activity = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        cpu_time_seconds = 1.337, )
                    ],
                total_count = 0,
                running_count = 0,
                starting_count = 0,
                stopped_count = 0,
                user_id = ''
            )
        else:
            return ListVmsResponse(
                vms = [
                    freestyle_client.models.vm_info.VmInfo(
                        id = '', 
                        state = 'starting', 
                        metrics = freestyle_client.models.vm_metrics_info.VmMetricsInfo(
                            wall_time_seconds = 0, 
                            billing_day = '', 
                            is_active_today = True, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_network_activity = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        cpu_time_seconds = 1.337, )
                    ],
                total_count = 0,
                running_count = 0,
                starting_count = 0,
                stopped_count = 0,
        )
        """

    def testListVmsResponse(self):
        """Test ListVmsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
