// This file is auto-generated by @hey-api/openapi-ts

/**
 * APIKey
 */
export type ApiKeyModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Created
     */
    created: number;
    /**
     * Last Used
     */
    last_used?: number | null;
};

/**
 * APIKeyList
 */
export type ApiKeyModelCollection = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Data
     */
    data: Array<ApiKeyModel>;
};

/**
 * BootInstanceFromImageRequest
 */
export type BootInstanceFromImageRequest = {
    /**
     * Vcpus
     * Number of vCPUs
     */
    vcpus?: number;
    /**
     * Memory
     * Memory in MB
     */
    memory?: number;
    /**
     * Disk Size
     * Size of the disk in MB. If not provided, defaults to the image's disk size.
     */
    disk_size?: number | null;
    /**
     * Metadata
     * Set of key-value pairs for storing additional information
     */
    metadata?: {
        [key: string]: string;
    } | null;
    /**
     * Ttl Seconds
     * Time to live in seconds for the instance. If not provided, the instance will not expire.
     */
    ttl_seconds?: number | null;
    /**
     * Ttl Action
     * Action to take when the instance expires. If not provided, the instance will not expire.
     */
    ttl_action?: ('stop' | 'pause') | null;
};

/**
 * BootInstanceRequest
 */
export type BootInstanceRequest = {
    /**
     * Vcpus
     */
    vcpus?: number | null;
    /**
     * Memory
     */
    memory?: number | null;
    /**
     * Disk Size
     */
    disk_size?: number | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    } | null;
    /**
     * Ttl Seconds
     * Time to live in seconds for the instance
     */
    ttl_seconds?: number | null;
    /**
     * Ttl Action
     * Action to take when the instance expires. Defaults to 'stop'.
     */
    ttl_action?: ('stop' | 'pause') | null;
};

/**
 * BranchInstanceRequest
 */
export type BranchInstanceRequest = {
    /**
     * Snapshot Metadata
     * Metadata for the new snapshot
     */
    snapshot_metadata?: {
        [key: string]: string;
    } | null;
    /**
     * Instance Metadata
     * Metadata for the new instances. If a list is provided, each instance will have the corresponding metadata.
     */
    instance_metadata?: {
        [key: string]: string;
    } | Array<{
        [key: string]: string;
    }> | null;
};

/**
 * BranchInstanceResponse
 */
export type BranchInstanceResponse = {
    snapshot: SnapshotModel;
    /**
     * Instances
     */
    instances: Array<InstanceModel>;
};

/**
 * CreateAPIKeyResponse
 */
export type CreateApiKeyResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Key
     */
    key: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Created
     */
    created: number;
};

/**
 * CreateSecretRequest
 */
export type CreateSecretRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Value
     */
    value: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * CreateSnapshotRequest
 */
export type CreateSnapshotRequest = {
    /**
     * Image Id
     * ID of the base image to use.
     */
    image_id?: string | null;
    /**
     * Configuration for checking instance readiness. Can be either a timeout-based check or an HTTP-based check.
     */
    readiness_check?: TimeoutCheck | null;
    /**
     * Vcpus
     * Number of vCPUs
     */
    vcpus?: number;
    /**
     * Memory
     * Memory in MB
     */
    memory?: number;
    /**
     * Disk Size
     * Size of the disk in MB
     */
    disk_size?: number;
    /**
     * Digest
     * User provided digest of the snapshot content
     */
    digest?: string | null;
    /**
     * Metadata
     * Set of key-value pairs for storing additional information
     */
    metadata?: {
        [key: string]: string;
    } | null;
};

/**
 * CreateSnapshotTokenResponse
 */
export type CreateSnapshotTokenResponse = {
    /**
     * Token
     */
    token: string;
    /**
     * Expires In
     */
    expires_in: number;
};

/**
 * InstanceExecRequest
 */
export type ExecRequest = {
    /**
     * Command
     */
    command: Array<string>;
};

/**
 * InstanceExecResponse
 */
export type ExecResponse = {
    /**
     * Stdout
     */
    stdout: string;
    /**
     * Stderr
     */
    stderr: string;
    /**
     * Exit Code
     */
    exit_code: number;
};

/**
 * ExposeHttpServiceRequest
 */
export type ExposeHttpServiceRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Port
     */
    port: number;
    /**
     * Authentication mode for the HTTP service
     */
    auth_mode?: HttpServiceAuthMode | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HttpServiceAuthMode
 */
export type HttpServiceAuthMode = 'none' | 'api_key';

/**
 * Image
 */
export type ImageModel = {
    /**
     * Id
     * Unique identifier for the base image, like img_xxxx
     */
    id: string;
    /**
     * Object
     * Object type, always 'image'
     */
    object?: 'image';
    /**
     * Created
     * Unix timestamp of when the base image was created
     */
    created: number;
    /**
     * Name
     * Name of the base image
     */
    name: string;
    /**
     * Description
     * Description of the base image
     */
    description?: string | null;
    /**
     * Disk Size
     * Size of the base image in bytes
     */
    disk_size: number;
};

/**
 * ImageList
 */
export type ImageModelCollection = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Data
     */
    data: Array<ImageModel>;
};

/**
 * InstanceExpireAction
 */
export type InstanceExpireAction = 'stop' | 'pause';

/**
 * InstanceHttpService
 */
export type InstanceHttpService = {
    /**
     * Name
     */
    name: string;
    /**
     * Port
     */
    port: number;
    /**
     * Url
     */
    url: string;
    auth_mode?: HttpServiceAuthMode;
};

/**
 * Instance
 */
export type InstanceModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Object
     */
    object?: 'instance';
    /**
     * Created
     */
    created: number;
    status?: InstanceStatus;
    spec: ResourceSpec;
    refs: InstanceRefs;
    networking: InstanceNetworking;
    /**
     * Metadata
     * User provided metadata for the instance
     */
    metadata?: {
        [key: string]: string;
    };
    /**
     * Time to live settings for the instance. If not set, the instance will not expire.
     */
    ttl: InstanceTtl;
    /**
     * Wake on settings for the instance. If not set, the instance will not wake on access.
     */
    wake_on: InstanceWakeOn;
};

/**
 * InstanceList
 */
export type InstanceModelCollection = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Data
     */
    data: Array<InstanceModel>;
};

/**
 * InstanceListPaginated
 */
export type InstanceModelCollectionPaginated = {
    /**
     * Instances
     */
    instances: Array<InstanceModel>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * InstanceNetworking
 */
export type InstanceNetworking = {
    /**
     * Internal Ip
     */
    internal_ip?: string | null;
    /**
     * Http Services
     */
    http_services?: Array<InstanceHttpService>;
};

/**
 * InstanceRefs
 */
export type InstanceRefs = {
    /**
     * Snapshot Id
     */
    snapshot_id: string;
    /**
     * Image Id
     */
    image_id: string;
};

/**
 * InstanceSshKey
 */
export type InstanceSshKey = {
    /**
     * Object
     */
    object?: 'instance_ssh_key';
    /**
     * Private Key
     */
    private_key: string;
    /**
     * Public Key
     */
    public_key: string;
    /**
     * Password
     */
    password: string;
    /**
     * Access Token
     */
    access_token: string;
};

/**
 * InstanceStatus
 */
export type InstanceStatus = 'pending' | 'ready' | 'paused' | 'saving' | 'error';

/**
 * InstanceTTL
 */
export type InstanceTtl = {
    /**
     * Ttl Seconds
     * Time to live in seconds for the instance
     */
    ttl_seconds: number | null;
    /**
     * Ttl Expire At
     * Unix timestamp of when the instance will expire
     */
    ttl_expire_at?: number | null;
    /**
     * Action to take when the instance expires
     */
    ttl_action?: InstanceExpireAction | null;
};

/**
 * InstanceWakeOn
 */
export type InstanceWakeOn = {
    /**
     * Wake On Ssh
     * Whether to wake the instance on SSH access
     */
    wake_on_ssh?: boolean;
    /**
     * Wake On Http
     * Whether to wake the instance on HTTP access
     */
    wake_on_http?: boolean;
};

/**
 * QuotaItemOut
 */
export type QuotaItemOut = {
    /**
     * Quota Code
     */
    quota_code: string;
    /**
     * Limit Value
     */
    limit_value: number;
    /**
     * Used Value
     */
    used_value: number;
};

/**
 * ResourceSpec
 */
export type ResourceSpec = {
    /**
     * Vcpus
     * VCPU Count of the snaphshot
     */
    vcpus: number;
    /**
     * Memory
     * Memory of the snaphshot in megabytes
     */
    memory: number;
    /**
     * Disk Size
     * Size of the snapshot in megabytes
     */
    disk_size: number;
};

/**
 * Secret
 */
export type SecretModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    };
    /**
     * Created
     */
    created: number;
    /**
     * Updated
     */
    updated: number;
};

/**
 * SecretList
 */
export type SecretModelCollection = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Data
     */
    data: Array<SecretModel>;
};

/**
 * ServiceQuotaItem
 */
export type ServiceQuotaItem = {
    /**
     * Service Id
     */
    service_id: string;
    /**
     * Service Name
     */
    service_name: string;
    /**
     * Quotas
     */
    quotas: Array<QuotaItemOut>;
};

/**
 * ServiceResourceBuckets
 */
export type ServiceResourceBuckets = {
    /**
     * Resource Type
     */
    resource_type: string;
    /**
     * Buckets
     */
    buckets: Array<UserServiceUsageBucket>;
};

/**
 * ServiceUsageItem
 */
export type ServiceUsageItem = {
    /**
     * Service Id
     */
    service_id: string;
    /**
     * Service Name
     */
    service_name: string;
    /**
     * Resource Types
     */
    resource_types: Array<ServiceResourceBuckets>;
};

/**
 * SnapshotInstanceRequest
 */
export type SnapshotInstanceRequest = {
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    } | null;
};

/**
 * Snapshot
 */
export type SnapshotModel = {
    /**
     * Id
     * Unique identifier for the snapshot, like snapshot_xxxx
     */
    id: string;
    /**
     * Object
     * Object type, always 'snapshot'
     */
    object?: 'snapshot';
    /**
     * Created
     * Unix timestamp of when the snapshot was created
     */
    created: number;
    /**
     * Status of the snapshot
     */
    status: SnapshotStatus;
    spec: ResourceSpec;
    refs: SnapshotRefs;
    /**
     * Digest
     * User provided digest of the snapshot content. Useful for caching if the snapshot takes a long time to create.
     */
    digest?: string | null;
    /**
     * Metadata
     * User provided metadata for the snapshot
     */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * SnapshotList
 */
export type SnapshotModelCollection = {
    /**
     * Object
     */
    object?: 'list';
    /**
     * Data
     */
    data: Array<SnapshotModel>;
};

/**
 * SnapshotListPaginated
 */
export type SnapshotModelCollectionPaginated = {
    /**
     * Snapshots
     */
    snapshots: Array<SnapshotModel>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * SnapshotRefs
 */
export type SnapshotRefs = {
    /**
     * Image Id
     */
    image_id: string;
};

/**
 * SnapshotStatus
 */
export type SnapshotStatus = 'pending' | 'ready' | 'failed' | 'deleting' | 'deleted';

/**
 * StartInstanceRequest
 */
export type StartInstanceRequest = {
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    } | null;
    /**
     * Ttl Seconds
     * Time to live in seconds for the instance
     */
    ttl_seconds?: number | null;
    /**
     * Ttl Action
     * Action to take when the instance expires. Defaults to 'stop'.
     */
    ttl_action?: ('stop' | 'pause') | null;
};

/**
 * TimeoutCheck
 */
export type TimeoutCheck = {
    /**
     * Type
     */
    type?: 'timeout';
    /**
     * Timeout
     */
    timeout?: number;
};

/**
 * UpdateSSHKeyRequest
 */
export type UpdateSshKeyRequest = {
    /**
     * Public Key
     */
    public_key: string;
};

/**
 * UpdateTTLRequest
 */
export type UpdateTtlRequest = {
    /**
     * Ttl Seconds
     * New TTL in seconds. To clear TTL pass null.
     */
    ttl_seconds: number | null;
    /**
     * Ttl Action
     * Action to take when the instance expires. Defaults to the current action or 'stop'.
     */
    ttl_action?: ('stop' | 'pause') | null;
};

/**
 * UpdateWakeRequest
 */
export type UpdateWakeRequest = {
    /**
     * Wake On Http
     * Whether to wake the instance on HTTP request
     */
    wake_on_http?: boolean;
    /**
     * Wake On Ssh
     * Whether to wake the instance on SSH request
     */
    wake_on_ssh?: boolean;
};

/**
 * UserInstanceUsage
 */
export type UserInstanceUsageModel = {
    /**
     * Instance Cpu Time
     */
    instance_cpu_time: number;
    /**
     * Instance Memory Time
     */
    instance_memory_time: number;
    /**
     * Instance Disk Time
     */
    instance_disk_time: number;
    /**
     * Period Start
     */
    period_start: number;
    /**
     * Period End
     */
    period_end: number;
};

/**
 * UserSSHKey
 */
export type UserSshKeyModel = {
    /**
     * Public Key
     */
    public_key: string;
    /**
     * Created
     */
    created: number;
};

/**
 * UserServiceQuotaResponse
 */
export type UserServiceQuotaResponse = {
    /**
     * Services
     */
    services: Array<ServiceQuotaItem>;
};

/**
 * UserServiceUsageBucket
 */
export type UserServiceUsageBucket = {
    /**
     * Period Start
     */
    period_start: number;
    /**
     * Period End
     */
    period_end: number;
    /**
     * Seconds
     */
    seconds: number;
    /**
     * Cents
     */
    cents: number;
};

/**
 * UserServiceUsageResponse
 */
export type UserServiceUsageResponse = {
    /**
     * Services
     */
    services: Array<ServiceUsageItem>;
};

/**
 * UserSnapshotUsage
 */
export type UserSnapshotUsageModel = {
    /**
     * Snapshot Memory Time
     */
    snapshot_memory_time: number;
    /**
     * Snapshot Disk Time
     */
    snapshot_disk_time: number;
    /**
     * Period Start
     */
    period_start: number;
    /**
     * Period End
     */
    period_end: number;
};

/**
 * UserUsageOverview
 */
export type UserUsageOverviewModel = {
    /**
     * Instance
     */
    instance: Array<UserInstanceUsageModel>;
    /**
     * Snapshot
     */
    snapshot: Array<UserSnapshotUsageModel>;
    /**
     * Items
     */
    items: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListImagesImageGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/image';
};

export type ListImagesImageGetResponses = {
    /**
     * Successful Response
     */
    200: ImageModelCollection;
};

export type ListImagesImageGetResponse = ListImagesImageGetResponses[keyof ListImagesImageGetResponses];

export type BootImageImageImageIdBootPostData = {
    body: BootInstanceFromImageRequest;
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/image/{image_id}/boot';
};

export type BootImageImageImageIdBootPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BootImageImageImageIdBootPostError = BootImageImageImageIdBootPostErrors[keyof BootImageImageImageIdBootPostErrors];

export type BootImageImageImageIdBootPostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type BootImageImageImageIdBootPostResponse = BootImageImageImageIdBootPostResponses[keyof BootImageImageImageIdBootPostResponses];

export type ListSnapshotsSnapshotGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Digest
         */
        digest?: string | null;
        /**
         * metadata[...] query parameters for filtering snapshots
         */
        metadata?: {
            [key: string]: string;
        };
    };
    url: '/snapshot';
};

export type ListSnapshotsSnapshotGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSnapshotsSnapshotGetError = ListSnapshotsSnapshotGetErrors[keyof ListSnapshotsSnapshotGetErrors];

export type ListSnapshotsSnapshotGetResponses = {
    /**
     * Successful Response
     */
    200: SnapshotModelCollection;
};

export type ListSnapshotsSnapshotGetResponse = ListSnapshotsSnapshotGetResponses[keyof ListSnapshotsSnapshotGetResponses];

export type CreateSnapshotSnapshotPostData = {
    body: CreateSnapshotRequest;
    path?: never;
    query?: never;
    url: '/snapshot';
};

export type CreateSnapshotSnapshotPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSnapshotSnapshotPostError = CreateSnapshotSnapshotPostErrors[keyof CreateSnapshotSnapshotPostErrors];

export type CreateSnapshotSnapshotPostResponses = {
    /**
     * Successful Response
     */
    200: SnapshotModel;
};

export type CreateSnapshotSnapshotPostResponse = CreateSnapshotSnapshotPostResponses[keyof CreateSnapshotSnapshotPostResponses];

export type ListSnapshotsPaginatedSnapshotListGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Digest
         */
        digest?: string | null;
        /**
         * Page
         * Page number (1-based)
         */
        page?: number;
        /**
         * Limit
         * Number of items per page
         */
        limit?: number;
        /**
         * metadata[...] query parameters for filtering snapshots
         */
        metadata?: {
            [key: string]: string;
        };
    };
    url: '/snapshot/list';
};

export type ListSnapshotsPaginatedSnapshotListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSnapshotsPaginatedSnapshotListGetError = ListSnapshotsPaginatedSnapshotListGetErrors[keyof ListSnapshotsPaginatedSnapshotListGetErrors];

export type ListSnapshotsPaginatedSnapshotListGetResponses = {
    /**
     * Successful Response
     */
    200: SnapshotModelCollectionPaginated;
};

export type ListSnapshotsPaginatedSnapshotListGetResponse = ListSnapshotsPaginatedSnapshotListGetResponses[keyof ListSnapshotsPaginatedSnapshotListGetResponses];

export type DeleteSnapshotSnapshotSnapshotIdDeleteData = {
    body?: never;
    path: {
        /**
         * Snapshot Id
         */
        snapshot_id: string;
    };
    query?: never;
    url: '/snapshot/{snapshot_id}';
};

export type DeleteSnapshotSnapshotSnapshotIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSnapshotSnapshotSnapshotIdDeleteError = DeleteSnapshotSnapshotSnapshotIdDeleteErrors[keyof DeleteSnapshotSnapshotSnapshotIdDeleteErrors];

export type DeleteSnapshotSnapshotSnapshotIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSnapshotSnapshotSnapshotIdDeleteResponse = DeleteSnapshotSnapshotSnapshotIdDeleteResponses[keyof DeleteSnapshotSnapshotSnapshotIdDeleteResponses];

export type GetSnapshotSnapshotSnapshotIdGetData = {
    body?: never;
    path: {
        /**
         * Snapshot Id
         */
        snapshot_id: string;
    };
    query?: never;
    url: '/snapshot/{snapshot_id}';
};

export type GetSnapshotSnapshotSnapshotIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSnapshotSnapshotSnapshotIdGetError = GetSnapshotSnapshotSnapshotIdGetErrors[keyof GetSnapshotSnapshotSnapshotIdGetErrors];

export type GetSnapshotSnapshotSnapshotIdGetResponses = {
    /**
     * Successful Response
     */
    200: SnapshotModel;
};

export type GetSnapshotSnapshotSnapshotIdGetResponse = GetSnapshotSnapshotSnapshotIdGetResponses[keyof GetSnapshotSnapshotSnapshotIdGetResponses];

export type SetSnapshotMetadataSnapshotSnapshotIdMetadataPostData = {
    /**
     * Metadata
     */
    body: {
        [key: string]: string;
    };
    path: {
        /**
         * Snapshot Id
         */
        snapshot_id: string;
    };
    query?: never;
    url: '/snapshot/{snapshot_id}/metadata';
};

export type SetSnapshotMetadataSnapshotSnapshotIdMetadataPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetSnapshotMetadataSnapshotSnapshotIdMetadataPostError = SetSnapshotMetadataSnapshotSnapshotIdMetadataPostErrors[keyof SetSnapshotMetadataSnapshotSnapshotIdMetadataPostErrors];

export type SetSnapshotMetadataSnapshotSnapshotIdMetadataPostResponses = {
    /**
     * Successful Response
     */
    200: SnapshotModel;
};

export type SetSnapshotMetadataSnapshotSnapshotIdMetadataPostResponse = SetSnapshotMetadataSnapshotSnapshotIdMetadataPostResponses[keyof SetSnapshotMetadataSnapshotSnapshotIdMetadataPostResponses];

export type ListInstancesInstanceGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * metadata[...] query parameters for filtering instances
         */
        metadata?: {
            [key: string]: string;
        };
    };
    url: '/instance';
};

export type ListInstancesInstanceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInstancesInstanceGetError = ListInstancesInstanceGetErrors[keyof ListInstancesInstanceGetErrors];

export type ListInstancesInstanceGetResponses = {
    /**
     * Successful Response
     */
    200: InstanceModelCollection;
};

export type ListInstancesInstanceGetResponse = ListInstancesInstanceGetResponses[keyof ListInstancesInstanceGetResponses];

export type StartInstanceInstancePostData = {
    /**
     * Request
     */
    body?: StartInstanceRequest | null;
    path?: never;
    query: {
        /**
         * Snapshot Id
         */
        snapshot_id: string;
    };
    url: '/instance';
};

export type StartInstanceInstancePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartInstanceInstancePostError = StartInstanceInstancePostErrors[keyof StartInstanceInstancePostErrors];

export type StartInstanceInstancePostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type StartInstanceInstancePostResponse = StartInstanceInstancePostResponses[keyof StartInstanceInstancePostResponses];

export type ListInstancesPaginatedInstanceListGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         * Page number (1-based)
         */
        page?: number;
        /**
         * Limit
         * Number of items per page
         */
        limit?: number;
        /**
         * metadata[...] query parameters for filtering instances
         */
        metadata?: {
            [key: string]: string;
        };
    };
    url: '/instance/list';
};

export type ListInstancesPaginatedInstanceListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInstancesPaginatedInstanceListGetError = ListInstancesPaginatedInstanceListGetErrors[keyof ListInstancesPaginatedInstanceListGetErrors];

export type ListInstancesPaginatedInstanceListGetResponses = {
    /**
     * Successful Response
     */
    200: InstanceModelCollectionPaginated;
};

export type ListInstancesPaginatedInstanceListGetResponse = ListInstancesPaginatedInstanceListGetResponses[keyof ListInstancesPaginatedInstanceListGetResponses];

export type StopInstanceInstanceInstanceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}';
};

export type StopInstanceInstanceInstanceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopInstanceInstanceInstanceIdDeleteError = StopInstanceInstanceInstanceIdDeleteErrors[keyof StopInstanceInstanceInstanceIdDeleteErrors];

export type StopInstanceInstanceInstanceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type StopInstanceInstanceInstanceIdDeleteResponse = StopInstanceInstanceInstanceIdDeleteResponses[keyof StopInstanceInstanceInstanceIdDeleteResponses];

export type GetInstanceInstanceInstanceIdGetData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}';
};

export type GetInstanceInstanceInstanceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInstanceInstanceInstanceIdGetError = GetInstanceInstanceInstanceIdGetErrors[keyof GetInstanceInstanceInstanceIdGetErrors];

export type GetInstanceInstanceInstanceIdGetResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type GetInstanceInstanceInstanceIdGetResponse = GetInstanceInstanceInstanceIdGetResponses[keyof GetInstanceInstanceInstanceIdGetResponses];

export type SnapshotInstanceInstanceInstanceIdSnapshotPostData = {
    /**
     * Request
     */
    body?: SnapshotInstanceRequest | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: {
        /**
         * Digest
         */
        digest?: string | null;
    };
    url: '/instance/{instance_id}/snapshot';
};

export type SnapshotInstanceInstanceInstanceIdSnapshotPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SnapshotInstanceInstanceInstanceIdSnapshotPostError = SnapshotInstanceInstanceInstanceIdSnapshotPostErrors[keyof SnapshotInstanceInstanceInstanceIdSnapshotPostErrors];

export type SnapshotInstanceInstanceInstanceIdSnapshotPostResponses = {
    /**
     * Successful Response
     */
    200: SnapshotModel;
};

export type SnapshotInstanceInstanceInstanceIdSnapshotPostResponse = SnapshotInstanceInstanceInstanceIdSnapshotPostResponses[keyof SnapshotInstanceInstanceInstanceIdSnapshotPostResponses];

export type BranchInstanceInstanceInstanceIdBranchPostData = {
    /**
     * Request
     */
    body?: BranchInstanceRequest | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: {
        /**
         * Count
         */
        count?: number;
        /**
         * Digest
         */
        digest?: string | null;
    };
    url: '/instance/{instance_id}/branch';
};

export type BranchInstanceInstanceInstanceIdBranchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BranchInstanceInstanceInstanceIdBranchPostError = BranchInstanceInstanceInstanceIdBranchPostErrors[keyof BranchInstanceInstanceInstanceIdBranchPostErrors];

export type BranchInstanceInstanceInstanceIdBranchPostResponses = {
    /**
     * Successful Response
     */
    200: BranchInstanceResponse;
};

export type BranchInstanceInstanceInstanceIdBranchPostResponse = BranchInstanceInstanceInstanceIdBranchPostResponses[keyof BranchInstanceInstanceInstanceIdBranchPostResponses];

export type GetSshKeyInstanceInstanceIdSshKeyGetData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/ssh/key';
};

export type GetSshKeyInstanceInstanceIdSshKeyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSshKeyInstanceInstanceIdSshKeyGetError = GetSshKeyInstanceInstanceIdSshKeyGetErrors[keyof GetSshKeyInstanceInstanceIdSshKeyGetErrors];

export type GetSshKeyInstanceInstanceIdSshKeyGetResponses = {
    /**
     * Successful Response
     */
    200: InstanceSshKey;
};

export type GetSshKeyInstanceInstanceIdSshKeyGetResponse = GetSshKeyInstanceInstanceIdSshKeyGetResponses[keyof GetSshKeyInstanceInstanceIdSshKeyGetResponses];

export type RotateSshKeyInstanceInstanceIdSshKeyPostData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/ssh/key';
};

export type RotateSshKeyInstanceInstanceIdSshKeyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RotateSshKeyInstanceInstanceIdSshKeyPostError = RotateSshKeyInstanceInstanceIdSshKeyPostErrors[keyof RotateSshKeyInstanceInstanceIdSshKeyPostErrors];

export type RotateSshKeyInstanceInstanceIdSshKeyPostResponses = {
    /**
     * Successful Response
     */
    200: InstanceSshKey;
};

export type RotateSshKeyInstanceInstanceIdSshKeyPostResponse = RotateSshKeyInstanceInstanceIdSshKeyPostResponses[keyof RotateSshKeyInstanceInstanceIdSshKeyPostResponses];

export type ExposeHttpServiceInstanceInstanceIdHttpPostData = {
    body: ExposeHttpServiceRequest;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/http';
};

export type ExposeHttpServiceInstanceInstanceIdHttpPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExposeHttpServiceInstanceInstanceIdHttpPostError = ExposeHttpServiceInstanceInstanceIdHttpPostErrors[keyof ExposeHttpServiceInstanceInstanceIdHttpPostErrors];

export type ExposeHttpServiceInstanceInstanceIdHttpPostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type ExposeHttpServiceInstanceInstanceIdHttpPostResponse = ExposeHttpServiceInstanceInstanceIdHttpPostResponses[keyof ExposeHttpServiceInstanceInstanceIdHttpPostResponses];

export type HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
        /**
         * Service Name
         */
        service_name: string;
    };
    query?: never;
    url: '/instance/{instance_id}/http/{service_name}';
};

export type HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteError = HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteErrors[keyof HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteErrors];

export type HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteResponse = HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteResponses[keyof HideHttpServiceInstanceInstanceIdHttpServiceNameDeleteResponses];

export type ExecInstanceInstanceIdExecPostData = {
    body: ExecRequest;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/exec';
};

export type ExecInstanceInstanceIdExecPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecInstanceInstanceIdExecPostError = ExecInstanceInstanceIdExecPostErrors[keyof ExecInstanceInstanceIdExecPostErrors];

export type ExecInstanceInstanceIdExecPostResponses = {
    /**
     * Successful Response
     */
    200: ExecResponse;
};

export type ExecInstanceInstanceIdExecPostResponse = ExecInstanceInstanceIdExecPostResponses[keyof ExecInstanceInstanceIdExecPostResponses];

export type ExecSseInstanceInstanceIdExecSsePostData = {
    body: ExecRequest;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/exec/sse';
};

export type ExecSseInstanceInstanceIdExecSsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecSseInstanceInstanceIdExecSsePostError = ExecSseInstanceInstanceIdExecSsePostErrors[keyof ExecSseInstanceInstanceIdExecSsePostErrors];

export type ExecSseInstanceInstanceIdExecSsePostResponses = {
    /**
     * Server-Sent Event stream
     */
    200: Blob | File;
};

export type ExecSseInstanceInstanceIdExecSsePostResponse = ExecSseInstanceInstanceIdExecSsePostResponses[keyof ExecSseInstanceInstanceIdExecSsePostResponses];

export type SetInstanceMetadataInstanceInstanceIdMetadataPostData = {
    /**
     * Metadata
     */
    body: {
        [key: string]: string;
    };
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/metadata';
};

export type SetInstanceMetadataInstanceInstanceIdMetadataPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetInstanceMetadataInstanceInstanceIdMetadataPostError = SetInstanceMetadataInstanceInstanceIdMetadataPostErrors[keyof SetInstanceMetadataInstanceInstanceIdMetadataPostErrors];

export type SetInstanceMetadataInstanceInstanceIdMetadataPostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type SetInstanceMetadataInstanceInstanceIdMetadataPostResponse = SetInstanceMetadataInstanceInstanceIdMetadataPostResponses[keyof SetInstanceMetadataInstanceInstanceIdMetadataPostResponses];

export type UpdateInstanceTtlInstanceInstanceIdTtlPostData = {
    body: UpdateTtlRequest;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/ttl';
};

export type UpdateInstanceTtlInstanceInstanceIdTtlPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateInstanceTtlInstanceInstanceIdTtlPostError = UpdateInstanceTtlInstanceInstanceIdTtlPostErrors[keyof UpdateInstanceTtlInstanceInstanceIdTtlPostErrors];

export type UpdateInstanceTtlInstanceInstanceIdTtlPostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type UpdateInstanceTtlInstanceInstanceIdTtlPostResponse = UpdateInstanceTtlInstanceInstanceIdTtlPostResponses[keyof UpdateInstanceTtlInstanceInstanceIdTtlPostResponses];

export type UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostData = {
    body: UpdateWakeRequest;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/wake-on';
};

export type UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostError = UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostErrors[keyof UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostErrors];

export type UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostResponse = UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostResponses[keyof UpdateInstanceWakeOnInstanceInstanceIdWakeOnPostResponses];

export type RebootInstanceInstanceInstanceIdRebootPostData = {
    /**
     * Request
     */
    body?: BootInstanceRequest | null;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/reboot';
};

export type RebootInstanceInstanceInstanceIdRebootPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RebootInstanceInstanceInstanceIdRebootPostError = RebootInstanceInstanceInstanceIdRebootPostErrors[keyof RebootInstanceInstanceInstanceIdRebootPostErrors];

export type RebootInstanceInstanceInstanceIdRebootPostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type RebootInstanceInstanceInstanceIdRebootPostResponse = RebootInstanceInstanceInstanceIdRebootPostResponses[keyof RebootInstanceInstanceInstanceIdRebootPostResponses];

export type BootInstanceSnapshotSnapshotIdBootPostData = {
    body: BootInstanceRequest;
    path: {
        /**
         * Snapshot Id
         */
        snapshot_id: string;
    };
    query?: never;
    url: '/snapshot/{snapshot_id}/boot';
};

export type BootInstanceSnapshotSnapshotIdBootPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BootInstanceSnapshotSnapshotIdBootPostError = BootInstanceSnapshotSnapshotIdBootPostErrors[keyof BootInstanceSnapshotSnapshotIdBootPostErrors];

export type BootInstanceSnapshotSnapshotIdBootPostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type BootInstanceSnapshotSnapshotIdBootPostResponse = BootInstanceSnapshotSnapshotIdBootPostResponses[keyof BootInstanceSnapshotSnapshotIdBootPostResponses];

export type CreateSnapshotTokenSnapshotSnapshotIdTokenPostData = {
    body?: never;
    path: {
        /**
         * Snapshot Id
         */
        snapshot_id: string;
    };
    query?: {
        /**
         * Expires In
         * Token expiration in seconds (default 1 hour)
         */
        expires_in?: number;
    };
    url: '/snapshot/{snapshot_id}/token';
};

export type CreateSnapshotTokenSnapshotSnapshotIdTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSnapshotTokenSnapshotSnapshotIdTokenPostError = CreateSnapshotTokenSnapshotSnapshotIdTokenPostErrors[keyof CreateSnapshotTokenSnapshotSnapshotIdTokenPostErrors];

export type CreateSnapshotTokenSnapshotSnapshotIdTokenPostResponses = {
    /**
     * Successful Response
     */
    200: CreateSnapshotTokenResponse;
};

export type CreateSnapshotTokenSnapshotSnapshotIdTokenPostResponse = CreateSnapshotTokenSnapshotSnapshotIdTokenPostResponses[keyof CreateSnapshotTokenSnapshotSnapshotIdTokenPostResponses];

export type PullSnapshotSnapshotPullPostData = {
    /**
     * Metadata
     */
    body?: {
        [key: string]: string;
    } | null;
    path?: never;
    query: {
        /**
         * Token
         * Snapshot sharing token
         */
        token: string;
        /**
         * Digest
         */
        digest?: string | null;
    };
    url: '/snapshot/pull';
};

export type PullSnapshotSnapshotPullPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PullSnapshotSnapshotPullPostError = PullSnapshotSnapshotPullPostErrors[keyof PullSnapshotSnapshotPullPostErrors];

export type PullSnapshotSnapshotPullPostResponses = {
    /**
     * Successful Response
     */
    200: SnapshotModel;
};

export type PullSnapshotSnapshotPullPostResponse = PullSnapshotSnapshotPullPostResponses[keyof PullSnapshotSnapshotPullPostResponses];

export type PauseInstanceInstanceInstanceIdPausePostData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: {
        /**
         * Snapshot
         * Whether to create a snapshot when pausing the instance. Defaults to false.
         */
        snapshot?: boolean | null;
    };
    url: '/instance/{instance_id}/pause';
};

export type PauseInstanceInstanceInstanceIdPausePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PauseInstanceInstanceInstanceIdPausePostError = PauseInstanceInstanceInstanceIdPausePostErrors[keyof PauseInstanceInstanceInstanceIdPausePostErrors];

export type PauseInstanceInstanceInstanceIdPausePostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type PauseInstanceInstanceInstanceIdPausePostResponse = PauseInstanceInstanceInstanceIdPausePostResponses[keyof PauseInstanceInstanceInstanceIdPausePostResponses];

export type ResumeInstanceInstanceInstanceIdResumePostData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/instance/{instance_id}/resume';
};

export type ResumeInstanceInstanceInstanceIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumeInstanceInstanceInstanceIdResumePostError = ResumeInstanceInstanceInstanceIdResumePostErrors[keyof ResumeInstanceInstanceInstanceIdResumePostErrors];

export type ResumeInstanceInstanceInstanceIdResumePostResponses = {
    /**
     * Successful Response
     */
    200: InstanceModel;
};

export type ResumeInstanceInstanceInstanceIdResumePostResponse = ResumeInstanceInstanceInstanceIdResumePostResponses[keyof ResumeInstanceInstanceInstanceIdResumePostResponses];

export type ListApiKeysUserApiKeyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/api-key';
};

export type ListApiKeysUserApiKeyGetResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyModelCollection;
};

export type ListApiKeysUserApiKeyGetResponse = ListApiKeysUserApiKeyGetResponses[keyof ListApiKeysUserApiKeyGetResponses];

export type CreateApiKeyUserApiKeyPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/api-key';
};

export type CreateApiKeyUserApiKeyPostResponses = {
    /**
     * Successful Response
     */
    200: CreateApiKeyResponse;
};

export type CreateApiKeyUserApiKeyPostResponse = CreateApiKeyUserApiKeyPostResponses[keyof CreateApiKeyUserApiKeyPostResponses];

export type DeleteApiKeyUserApiKeyApiKeyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Api Key Id
         */
        api_key_id: string;
    };
    query?: never;
    url: '/user/api-key/{api_key_id}';
};

export type DeleteApiKeyUserApiKeyApiKeyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiKeyUserApiKeyApiKeyIdDeleteError = DeleteApiKeyUserApiKeyApiKeyIdDeleteErrors[keyof DeleteApiKeyUserApiKeyApiKeyIdDeleteErrors];

export type DeleteApiKeyUserApiKeyApiKeyIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiKeyUserApiKeyApiKeyIdDeleteResponse = DeleteApiKeyUserApiKeyApiKeyIdDeleteResponses[keyof DeleteApiKeyUserApiKeyApiKeyIdDeleteResponses];

export type ListSecretsUserSecretGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/secret';
};

export type ListSecretsUserSecretGetResponses = {
    /**
     * Successful Response
     */
    200: SecretModelCollection;
};

export type ListSecretsUserSecretGetResponse = ListSecretsUserSecretGetResponses[keyof ListSecretsUserSecretGetResponses];

export type CreateSecretUserSecretPostData = {
    body: CreateSecretRequest;
    path?: never;
    query?: never;
    url: '/user/secret';
};

export type CreateSecretUserSecretPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSecretUserSecretPostError = CreateSecretUserSecretPostErrors[keyof CreateSecretUserSecretPostErrors];

export type CreateSecretUserSecretPostResponses = {
    /**
     * Successful Response
     */
    200: SecretModel;
};

export type CreateSecretUserSecretPostResponse = CreateSecretUserSecretPostResponses[keyof CreateSecretUserSecretPostResponses];

export type DeleteSecretUserSecretSecretNameDeleteData = {
    body?: never;
    path: {
        /**
         * Secret Name
         */
        secret_name: string;
    };
    query?: never;
    url: '/user/secret/{secret_name}';
};

export type DeleteSecretUserSecretSecretNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSecretUserSecretSecretNameDeleteError = DeleteSecretUserSecretSecretNameDeleteErrors[keyof DeleteSecretUserSecretSecretNameDeleteErrors];

export type DeleteSecretUserSecretSecretNameDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSecretUserSecretSecretNameDeleteResponse = DeleteSecretUserSecretSecretNameDeleteResponses[keyof DeleteSecretUserSecretSecretNameDeleteResponses];

export type GetUserSshKeyUserSshKeyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/ssh-key';
};

export type GetUserSshKeyUserSshKeyGetResponses = {
    /**
     * Successful Response
     */
    200: UserSshKeyModel;
};

export type GetUserSshKeyUserSshKeyGetResponse = GetUserSshKeyUserSshKeyGetResponses[keyof GetUserSshKeyUserSshKeyGetResponses];

export type UpdateUserSshKeyUserSshKeyPutData = {
    body: UpdateSshKeyRequest;
    path?: never;
    query?: never;
    url: '/user/ssh-key';
};

export type UpdateUserSshKeyUserSshKeyPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserSshKeyUserSshKeyPutError = UpdateUserSshKeyUserSshKeyPutErrors[keyof UpdateUserSshKeyUserSshKeyPutErrors];

export type UpdateUserSshKeyUserSshKeyPutResponses = {
    /**
     * Successful Response
     */
    200: UserSshKeyModel;
};

export type UpdateUserSshKeyUserSshKeyPutResponse = UpdateUserSshKeyUserSshKeyPutResponses[keyof UpdateUserSshKeyUserSshKeyPutResponses];

export type GetUserUsageUserUsageGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Interval
         */
        interval?: string;
    };
    url: '/user/usage';
};

export type GetUserUsageUserUsageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserUsageUserUsageGetError = GetUserUsageUserUsageGetErrors[keyof GetUserUsageUserUsageGetErrors];

export type GetUserUsageUserUsageGetResponses = {
    /**
     * Successful Response
     */
    200: UserUsageOverviewModel;
};

export type GetUserUsageUserUsageGetResponse = GetUserUsageUserUsageGetResponses[keyof GetUserUsageUserUsageGetResponses];

export type GetUserServiceUsageUserServiceUsageGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Interval
         */
        interval?: string;
    };
    url: '/user/service/usage';
};

export type GetUserServiceUsageUserServiceUsageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserServiceUsageUserServiceUsageGetError = GetUserServiceUsageUserServiceUsageGetErrors[keyof GetUserServiceUsageUserServiceUsageGetErrors];

export type GetUserServiceUsageUserServiceUsageGetResponses = {
    /**
     * Successful Response
     */
    200: UserServiceUsageResponse;
};

export type GetUserServiceUsageUserServiceUsageGetResponse = GetUserServiceUsageUserServiceUsageGetResponses[keyof GetUserServiceUsageUserServiceUsageGetResponses];

export type GetUserServiceQuotaUserServiceQuotaGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/service/quota';
};

export type GetUserServiceQuotaUserServiceQuotaGetResponses = {
    /**
     * Successful Response
     */
    200: UserServiceQuotaResponse;
};

export type GetUserServiceQuotaUserServiceQuotaGetResponse = GetUserServiceQuotaUserServiceQuotaGetResponses[keyof GetUserServiceQuotaUserServiceQuotaGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};