"use node";
import { v } from "convex/values";
import { fetchInstallationAccessToken } from "../_shared/githubApp";
import { internal } from "./_generated/api";
import type { Doc, Id } from "./_generated/dataModel";
import {
  internalAction,
  type ActionCtx,
} from "./_generated/server";
import { Octokit } from "octokit";

const createOctokit = (token: string): Octokit => {
  return new Octokit({
    auth: token,
    userAgent: "cmux-github-bot",
    request: {
      timeout: 10_000,
    },
  });
};

const parseRepoFullName = (
  repoFullName: string,
): { owner: string; repo: string } | null => {
  const [owner, repo] = repoFullName.split("/");
  if (!owner || !repo) {
    return null;
  }
  return { owner, repo };
};

type PreviewRunDoc = Doc<"previewRuns">;
type ScreenshotSetDoc = Doc<"previewScreenshotSets">;

const COMMENT_SIGNATURE = "_Generated by [cmux](https://cmux.dev)";
const COLLAPSE_MARKER = "<!-- cmux-preview-collapsed -->";
const COLLAPSE_SUMMARY = "Older cmux preview screenshots (latest comment is above)";
const MAX_COMMENTS_TO_COLLAPSE = 20;
const MAX_PREVIOUS_SCREENSHOT_SETS = 5;
const NON_UI_CHANGE_PATTERNS = [
  /no changes detected/i,
  /all changed files are binary/i,
];
const STATUS_SUMMARY_LABEL: Record<ScreenshotSetDoc["status"], string> = {
  completed: "✅ Screenshots",
  failed: "❌ Failed",
  skipped: "⚠️ Skipped",
};

const formatTimestamp = (value?: number | null): string => {
  if (!value) {
    return "unknown time";
  }
  return new Date(value).toISOString().replace("T", " ").replace("Z", " UTC");
};

const formatCommitLabel = (set: ScreenshotSetDoc): string =>
  set.commitSha ? `\`${set.commitSha.slice(0, 7)}\`` : "latest commit";

const isNonUiChangeReason = (reason?: string | null): boolean => {
  if (!reason) {
    return false;
  }
  return NON_UI_CHANGE_PATTERNS.some((pattern) => pattern.test(reason));
};

const formatSkippedMessage = (reason?: string | null): string => {
  if (isNonUiChangeReason(reason)) {
    return [
      "No UI-impacting changes were detected, so screenshots were skipped.",
      reason ? `> ${reason}` : null,
    ]
      .filter(Boolean)
      .join("\n\n");
  }
  if (reason) {
    return `Screenshot capture was skipped.\n\n> ${reason}`;
  }
  return "Screenshot capture was skipped.";
};

const summarizeSet = (
  set: ScreenshotSetDoc,
  run?: PreviewRunDoc,
): string => {
  const prefix = STATUS_SUMMARY_LABEL[set.status] ?? "ℹ️ Preview";
  const commit = set.commitSha ? set.commitSha.slice(0, 7) : "unknown";
  const timestamp = formatTimestamp(set.capturedAt ?? run?.createdAt);
  return `${prefix} – commit ${commit} (${timestamp})`;
};

async function renderScreenshotSetMarkdown(
  ctx: ActionCtx,
  set: ScreenshotSetDoc,
  heading: string,
  linksRow?: string,
): Promise<string> {
  const commitLabel = formatCommitLabel(set);
  const timestamp = formatTimestamp(set.capturedAt);
  const lines: string[] = [heading, ""];

  if (set.status === "completed" && set.images.length > 0) {
    const count = set.images.length;
    const intro = `Captured ${count} screenshot${count === 1 ? "" : "s"} for commit ${commitLabel} (${timestamp}).`;
    lines.push(intro, "");
    if (linksRow) {
      lines.push(linksRow, "");
    }
    for (const image of set.images) {
      const storageUrl = await ctx.storage.getUrl(image.storageId);
      if (!storageUrl) continue;
      const fileName = image.fileName || "screenshot";
      lines.push(`![${fileName}](${storageUrl})`, "");
    }
  } else if (set.status === "failed") {
    lines.push(
      `Failed to capture screenshots for commit ${commitLabel}.`,
      "",
      set.error ? `> ${set.error}` : "> Unknown error",
      "",
    );
  } else if (set.status === "skipped") {
    lines.push(formatSkippedMessage(set.error), "");
  } else {
    lines.push("Screenshot status is unknown for this run.", "");
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd();
}

const collapseCommentBody = (body: string): string => {
  const trimmed = body.trim();
  if (trimmed.includes(COLLAPSE_MARKER)) {
    return trimmed;
  }
  return [
    COLLAPSE_MARKER,
    "<details>",
    `<summary>${COLLAPSE_SUMMARY}</summary>`,
    "",
    trimmed,
    "",
    "</details>",
  ]
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd();
};

async function collapseOlderPreviewComments({
  octokit,
  owner,
  repo,
  prNumber,
  latestCommentId,
}: {
  octokit: Octokit;
  owner: string;
  repo: string;
  prNumber: number;
  latestCommentId: number;
}): Promise<void> {
  let collapsedCount = 0;
  const iterator = octokit.paginate.iterator(
    octokit.rest.issues.listComments,
    {
      owner,
      repo,
      issue_number: prNumber,
      per_page: 50,
    },
  );

  for await (const { data } of iterator) {
    for (const comment of data) {
      if (collapsedCount >= MAX_COMMENTS_TO_COLLAPSE) {
        return;
      }
      if (!comment.body) continue;
      if (comment.id === latestCommentId) continue;
      if (!comment.body.includes(COMMENT_SIGNATURE)) continue;

      const nextBody = collapseCommentBody(comment.body);
      if (nextBody === comment.body) continue;

      try {
        await octokit.rest.issues.updateComment({
          owner,
          repo,
          comment_id: comment.id,
          body: nextBody,
        });
        collapsedCount += 1;
        console.log("[github_pr_comments] Collapsed previous preview comment", {
          commentId: comment.id,
        });
      } catch (error) {
        console.error(
          "[github_pr_comments] Failed to collapse previous preview comment",
          {
            commentId: comment.id,
            error,
          },
        );
      }
    }
  }
}

export const addPrReaction = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    content: v.literal("eyes"),
  },
  handler: async (
    _ctx,
    { installationId, repoFullName, prNumber, content },
  ) => {
    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for installation",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      const repo = parseRepoFullName(repoFullName);
      if (!repo) {
        console.error("[github_pr_comments] Invalid repo full name", {
          repoFullName,
        });
        return {
          ok: false,
          error: "Invalid repository name",
        };
      }

      const octokit = createOctokit(accessToken);
      const { data } = await octokit.rest.reactions.createForIssue({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: prNumber,
        content,
      });

      console.log("[github_pr_comments] Successfully added reaction", {
        installationId,
        repoFullName,
        prNumber,
        reactionId: data.id,
      });

      return { ok: true, reactionId: data.id };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error adding reaction",
        {
          installationId,
          repoFullName,
          prNumber,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

export const postPreviewComment = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    screenshotSetId: v.id("previewScreenshotSets"),
    previewRunId: v.id("previewRuns"),
  },
  handler: async (ctx, args) => {
    const { installationId, repoFullName, prNumber, screenshotSetId } = args;

    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for preview comment",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      const repo = parseRepoFullName(repoFullName);
      if (!repo) {
        console.error("[github_pr_comments] Invalid repo full name", {
          repoFullName,
        });
        return { ok: false, error: "Invalid repository name" };
      }

      const octokit = createOctokit(accessToken);

      const previewRunPayload = await ctx.runQuery(
        internal.previewRuns.getRunWithConfig,
        { previewRunId: args.previewRunId },
      );
      const previewRun = previewRunPayload?.run;
      if (!previewRun) {
        console.error("[github_pr_comments] Preview run not found", {
          previewRunId: args.previewRunId,
        });
        return { ok: false, error: "Preview run not found" };
      }

      // Get screenshot set
      const screenshotSet = await ctx.runQuery(
        internal.previewScreenshots.getScreenshotSet,
        { screenshotSetId },
      );

      if (!screenshotSet) {
        console.error("[github_pr_comments] Screenshot set not found", {
          screenshotSetId,
        });
        return { ok: false, error: "Screenshot set not found" };
      }

      // Get taskRun if available for workspace/dev browser URLs
      let workspaceUrl: string | undefined;
      let devServerUrl: string | undefined;
      if (previewRun.taskRunId) {
        const taskRun = await ctx.runQuery(internal.taskRuns.getById, {
          id: previewRun.taskRunId,
        });
        if (taskRun) {
          // Get team info for the URL
          const team = await ctx.runQuery(internal.teams.getByTeamIdInternal, {
            teamId: taskRun.teamId,
          });
          const teamSlug: string = team?.slug ?? taskRun.teamId;
          workspaceUrl = `https://cmux.dev/${teamSlug}/task/${taskRun.taskId}`;
          devServerUrl = taskRun.vscode?.ports?.proxy;
        }
      }

      // Collect previous screenshot sets for this PR so we can collapse them
      const previousRuns =
        (await ctx.runQuery(internal.previewRuns.listByConfigAndPr, {
          previewConfigId: previewRun.previewConfigId,
          prNumber: previewRun.prNumber,
          limit: MAX_PREVIOUS_SCREENSHOT_SETS + 1,
        })) ?? [];

      const previousSetEntries: Array<{
        run: PreviewRunDoc;
        set: ScreenshotSetDoc;
      }> = [];
      for (const run of previousRuns) {
        if (run._id === previewRun._id) continue;
        if (!run.screenshotSetId) continue;
        const priorSet = await ctx.runQuery(
          internal.previewScreenshots.getScreenshotSet,
          { screenshotSetId: run.screenshotSetId },
        );
        if (!priorSet) continue;
        previousSetEntries.push({ run, set: priorSet });
        if (previousSetEntries.length >= MAX_PREVIOUS_SCREENSHOT_SETS) {
          break;
        }
      }

      // Build links row (under the heading, above screenshots)
      const linkParts: string[] = [];
      if (workspaceUrl) {
        linkParts.push(`[Open Workspace (1 hr)](${workspaceUrl}?src=preview.new)`);
      }
      if (devServerUrl) {
        linkParts.push(`[Open Dev Browser (1 hr)](${devServerUrl}?src=preview.new)`);
      }
      linkParts.push(`[Open Diff Heatmap](https://0github.com/${repoFullName}/pull/${prNumber}?src=preview.new)`);
      const linksRow = linkParts.join(" • ");

      // Build comment body
      const latestHeading = `### Latest commit ${formatCommitLabel(screenshotSet)}`;
      const latestSection = await renderScreenshotSetMarkdown(
        ctx,
        screenshotSet,
        latestHeading,
        linksRow,
      );

      const commentSections: string[] = ["## Preview Screenshots", latestSection];

      if (previousSetEntries.length > 0) {
        const collapsedSections: string[] = [];
        for (const entry of previousSetEntries) {
          const sectionHeading = `#### ${summarizeSet(entry.set, entry.run)}`;
          collapsedSections.push(
            await renderScreenshotSetMarkdown(ctx, entry.set, sectionHeading),
          );
        }

        const previousBlock = [
          "<details>",
          `<summary>Previous preview runs (${previousSetEntries.length})</summary>`,
          "",
          collapsedSections.join("\n\n---\n\n"),
          "",
          "</details>",
        ].join("\n");

        commentSections.push(previousBlock);
      }

      commentSections.push("---", COMMENT_SIGNATURE);
      const commentBody = commentSections.join("\n\n");

      // Post comment to GitHub
      const { data } = await octokit.rest.issues.createComment({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: prNumber,
        body: commentBody,
      });

      console.log("[github_pr_comments] Successfully posted preview comment", {
        installationId,
        repoFullName,
        prNumber,
        commentId: data.id,
        commentUrl: data.html_url,
      });

      // Update preview run with comment URL
      if (data.html_url) {
        await ctx.runMutation(internal.previewRuns.updateStatus, {
          previewRunId: args.previewRunId,
          status: "completed",
          screenshotSetId,
          githubCommentUrl: data.html_url,
          githubCommentId: data.id,
        });
      }

      await collapseOlderPreviewComments({
        octokit,
        owner: repo.owner,
        repo: repo.repo,
        prNumber,
        latestCommentId: data.id,
      });

      return { ok: true, commentId: data.id, commentUrl: data.html_url };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error posting preview comment",
        {
          installationId,
          repoFullName,
          prNumber,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

export const addPrComment = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    body: v.string(),
  },
  handler: async (
    _ctx,
    { installationId, repoFullName, prNumber, body },
  ) => {
    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for installation",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      const repo = parseRepoFullName(repoFullName);
      if (!repo) {
        console.error("[github_pr_comments] Invalid repo full name", {
          repoFullName,
        });
        return { ok: false, error: "Invalid repository name" };
      }

      const octokit = createOctokit(accessToken);
      const { data } = await octokit.rest.issues.createComment({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: prNumber,
        body,
      });
      console.log("[github_pr_comments] Successfully added comment", {
        installationId,
        repoFullName,
        prNumber,
        commentId: data.id,
      });

      return { ok: true, commentId: data.id };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error adding comment",
        {
          installationId,
          repoFullName,
          prNumber,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

async function getScreenshotsForPr(
  ctx: ActionCtx,
  {
    teamId,
    repoFullName,
    prNumber,
  }: {
    teamId: string;
    repoFullName: string;
    prNumber: number;
  },
): Promise<Array<{ url: string; fileName?: string }>> {
  try {
    // Find task runs that have this PR
    const taskRuns = await ctx.runQuery(
      internal.github_pr_queries.findTaskRunsForPr,
      {
        teamId,
        repoFullName,
        prNumber,
      },
    );

    if (taskRuns.length === 0) {
      return [];
    }

    // Get screenshots from the latest task run
    const screenshots: Array<{ url: string; fileName?: string }> = [];

    for (const run of taskRuns) {
      if (run.latestScreenshotSetId) {
        const screenshotSet = await ctx.runQuery(
          internal.github_pr_queries.getScreenshotSet,
          {
            screenshotSetId: run.latestScreenshotSetId,
          },
        );

        if (screenshotSet && screenshotSet.status === "completed") {
          for (const image of screenshotSet.images) {
            if (image.url) {
              screenshots.push({
                url: image.url,
                fileName: image.fileName,
              });
            }
          }
        }
      }
    }

    return screenshots;
  } catch (error) {
    console.error(
      "[github_pr_comments] Error fetching screenshots for PR",
      {
        teamId,
        repoFullName,
        prNumber,
        error,
      },
    );
    return [];
  }
}

function formatScreenshotComment(
  screenshots: Array<{ url: string; fileName?: string }>,
): string {
  if (screenshots.length === 0) {
    return "";
  }

  let markdown = "## Screenshots\n\n";
  markdown +=
    "Here are the screenshots from the latest run:\n\n";

  for (const screenshot of screenshots) {
    const title = screenshot.fileName || "Screenshot";
    markdown += `### ${title}\n\n`;
    markdown += `![${title}](${screenshot.url})\n\n`;
  }

  return markdown;
}

export const postPreviewCommentWithTaskScreenshots = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    taskRunId: v.id("taskRuns"),
    previewRunId: v.id("previewRuns"),
  },
  handler: async (ctx, args): Promise<{ ok: true; commentId?: number; commentUrl?: string } | { ok: false; error: string }> => {
    const { installationId, repoFullName, prNumber, taskRunId, previewRunId } = args;

    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for preview comment",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      const repo = parseRepoFullName(repoFullName);
      if (!repo) {
        console.error("[github_pr_comments] Invalid repo full name", {
          repoFullName,
        });
        return { ok: false, error: "Invalid repository name" };
      }

      const octokit = createOctokit(accessToken);

      // Get task run to find screenshot set
      const taskRun = await ctx.runQuery(internal.taskRuns.getById, {
        id: taskRunId,
      });

      if (!taskRun?.latestScreenshotSetId) {
        console.error("[github_pr_comments] No screenshot set for task run", {
          taskRunId,
        });
        return { ok: false, error: "No screenshot set found" };
      }

      const previewRun = await ctx.runQuery(internal.previewRuns.getById, {
        id: previewRunId,
      });

      if (!previewRun) {
        console.error("[github_pr_comments] Preview run not found", {
          previewRunId,
        });
        return { ok: false, error: "Preview run not found" };
      }

      // Get team info for the URL
      const team = await ctx.runQuery(internal.teams.getByTeamIdInternal, {
        teamId: taskRun.teamId,
      });
      const teamSlug: string = team?.slug ?? taskRun.teamId;
      const workspaceUrl: string = `https://cmux.dev/${teamSlug}/task/${taskRun.taskId}`;

      // Get screenshot set from task run
      const screenshotSet = await ctx.runQuery(
        internal.github_pr_queries.getScreenshotSet,
        { screenshotSetId: taskRun.latestScreenshotSetId },
      );

      if (!screenshotSet) {
        console.error("[github_pr_comments] Screenshot set not found", {
          screenshotSetId: taskRun.latestScreenshotSetId,
        });
        return { ok: false, error: "Screenshot set not found" };
      }

      // Build comment body
      const devServerUrl = taskRun.vscode?.ports?.proxy;

      // Build links row (under the heading, above screenshots)
      const linkParts: string[] = [];
      if (workspaceUrl) {
        linkParts.push(`[Open Workspace (1 hr)](${workspaceUrl}?src=preview.new)`);
      }
      if (devServerUrl) {
        linkParts.push(`[Open Dev Browser (1 hr)](${devServerUrl}?src=preview.new)`);
      }
      linkParts.push(`[Open Diff Heatmap](https://0github.com/${repoFullName}/pull/${prNumber}?src=preview.new)`);
      const linksRow = linkParts.join(" • ");

      let commentBody: string = "## Preview Screenshots\n\n";

      if (screenshotSet.status === "completed" && screenshotSet.images.length > 0) {
        commentBody += `Successfully captured ${screenshotSet.images.length} screenshot(s) for commit \`${(screenshotSet.commitSha || "").slice(0, 7)}\`:\n\n`;
        commentBody += `${linksRow}\n\n`;

        for (const image of screenshotSet.images) {
          // Get storage URL for the image
          const storageUrl = await ctx.storage.getUrl(image.storageId);
          if (storageUrl) {
            const fileName = image.fileName || "screenshot";
            commentBody += `### ${fileName}\n`;
            commentBody += `![${fileName}](${storageUrl})\n\n`;
          }
        }

        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev) preview system_`;
      } else if (screenshotSet.status === "failed") {
        commentBody += `Failed to capture screenshots: ${screenshotSet.error || "Unknown error"}\n\n`;
        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev) preview system_`;
      } else if (screenshotSet.status === "skipped") {
        commentBody += `Screenshot capture was skipped: ${screenshotSet.error || "No preview configured"}\n\n`;
        commentBody += `\n---\n_Generated by [cmux](https://cmux.dev) preview system_`;
      }

      // Post comment to GitHub
      const { data } = await octokit.rest.issues.createComment({
        owner: repo.owner,
        repo: repo.repo,
        issue_number: prNumber,
        body: commentBody,
      });
      console.log("[github_pr_comments] Successfully posted preview comment", {
        installationId,
        repoFullName,
        prNumber,
        commentId: data.id,
        commentUrl: data.html_url,
      });

      const previewScreenshotSetId = await ctx.runMutation(
        internal.previewScreenshots.createScreenshotSet,
        {
          previewRunId,
          status: screenshotSet.status as "completed" | "failed" | "skipped",
          commitSha: screenshotSet.commitSha ?? previewRun.headSha,
          error: screenshotSet.error,
          images: screenshotSet.images.map((image) => ({
            storageId: image.storageId as Id<"_storage">,
            mimeType: image.mimeType,
            fileName: image.fileName,
            commitSha: image.commitSha,
          })),
        },
      );

      // Update preview run with comment URL
      if (data.html_url) {
        await ctx.runMutation(internal.previewRuns.updateStatus, {
          previewRunId,
          status: screenshotSet.status as "completed" | "failed" | "skipped",
          stateReason: screenshotSet.error,
          screenshotSetId: previewScreenshotSetId,
          githubCommentUrl: data.html_url,
        });
      }

      return { ok: true, commentId: data.id, commentUrl: data.html_url };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error posting preview comment",
        {
          installationId,
          repoFullName,
          prNumber,
          taskRunId,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

export const addScreenshotCommentToPr = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    teamId: v.string(),
  },
  handler: async (
    ctx,
    { installationId, repoFullName, prNumber, teamId },
  ): Promise<
    | { ok: true; commentId?: number; skipped?: boolean; reason?: string }
    | { ok: false; error: string }
  > => {
    try {
      const screenshots = await getScreenshotsForPr(ctx, {
        teamId,
        repoFullName,
        prNumber,
      });

      if (screenshots.length === 0) {
        console.log(
          "[github_pr_comments] No screenshots found for PR",
          {
            installationId,
            repoFullName,
            prNumber,
          },
        );
        return { ok: true, skipped: true, reason: "No screenshots found" };
      }

      const body = formatScreenshotComment(screenshots);

      const result = await ctx.runAction(internal.github_pr_comments.addPrComment, {
        installationId,
        repoFullName,
        prNumber,
        body,
      });

      if (result.ok) {
        return { ok: true, commentId: result.commentId };
      }

      return { ok: false, error: result?.error ?? "Unknown error" };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error adding screenshot comment",
        {
          installationId,
          repoFullName,
          prNumber,
          teamId,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});
